create sequence hibernate_sequence
  start with 1
  increment by 1;

create table constraint_excludes (
  id                    bigint not null,
  for_product_id        bigint,
  excluded_feature_name varchar(255),
  source_feature_name   varchar(255),
  primary key (id)
);

create table constraint_requires (
  id                    bigint not null,
  for_product_id        bigint,
  required_feature_name varchar(255),
  source_feature_name   varchar(255),
  primary key (id)
);

create table feature (
  id          bigint generated by default as identity,
  description varchar(255),
  name        varchar(255) not null,
  product_id  bigint,
  primary key (id)
);

create table product (
  id   bigint generated by default as identity,
  name varchar(255) not null,
  primary key (id)
);

create table product_configuration (
  id         bigint generated by default as identity,
  name       varchar(255) not null,
  valid      boolean,
  product_id bigint,
  primary key (id)
);

create table product_configuration_actived_features (
  in_configurations_id bigint not null,
  actived_features_id  bigint not null,
  primary key (in_configurations_id, actived_features_id)
);

alter table constraint_excludes
  add constraint FK_blafpc49ar2njme3soh8lyirpforeign foreign key (for_product_id) references product;

alter table constraint_requires
  add constraint FK_77bc87w5luaf5ulfs18ctw2df foreign key (for_product_id) references product;

alter table feature
  add constraint FK810l56o2f4ev18qmd4434tqnw foreign key (product_id) references product;

alter table product_configuration
  add constraint FKhjiv1whgr5b8vhm2tkc2jed95 foreign key (product_id) references product;

alter table product_configuration_actived_features
  add constraint FKh6xt6rco9nhy67ykkp2en7miw foreign key (actived_features_id) references feature;

alter table product_configuration_actived_features
  add constraint FKtdpo2lujpc2j7guhlatsucp75 foreign key (in_configurations_id) references product_configuration;