create table admin_settings_aud (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    excel_batch_size integer,
    reboot_server boolean,
    primary key (id, rev));

create table admin_settings (
    id bigint generated by default as identity,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    excel_batch_size integer,
    reboot_server boolean,
    primary key (id));

create table category (
    dtype varchar(100) not null,
    id bigint generated by default as identity,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    description varchar(255),
    label varchar(255),
    primary key (id));

create table category_aud (
    id bigint not null,
    rev integer not null,
    dtype varchar(100) not null,
    revtype smallint,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    description varchar(255),
    label varchar(255),
    primary key (id, rev));

create table file_metadata_aud (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    content_type varchar(255),
    is_user_support_document boolean,
    name varchar(255),
    size bigint,
    content_id bigint,
    primary key (id, rev));

create table file_content (
    id bigint generated by default as identity,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    bytes blob,
    primary key (id));

create table file_metadata (
    id bigint generated by default as identity,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    content_type varchar(255),
    is_user_support_document boolean not null,
    name varchar(255),
    size bigint not null,
    content_id bigint,
    primary key (id));

create table person (
    id bigint generated by default as identity,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    change_password boolean,
    country varchar(255),
    email varchar(255),
    enabled boolean,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    secret varchar(255),
    title varchar(255),
    username varchar(255),
    default_dashboard_id bigint,
    group_id bigint,
    primary key (id));

create table person_aud (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    change_password boolean,
    country varchar(255),
    email varchar(255),
    enabled boolean,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    secret varchar(255),
    title varchar(255),
    username varchar(255),
    default_dashboard_id bigint,
    group_id bigint,
    primary key (id, rev));


create table person_roles (
    person_id bigint not null,
    roles_id bigint not null);

create table person_roles_aud (
    rev integer not null,
    person_id bigint not null,
    roles_id bigint not null,
    revtype smallint,
    primary key (rev, person_id, roles_id));

create table revinfo (
    rev integer generated by default as identity,
    revtstmp bigint,
    primary key (rev));

create table role (
    id bigint generated by default as identity,
    authority varchar(255),
    primary key (id));

create table role_aud (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    authority varchar(255),
    primary key (id, rev));

create table test_form_aud (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    checkbox boolean,
    checkbox_picker boolean,
    checkbox_toggle boolean,
    date timestamp,
    date_time timestamp,
    summernote varchar(32000),
    text_area varchar(32000),
    text_field varchar(255),
    entity_select_id bigint,
    preloaded_entity_select_id bigint,
    primary key (id, rev));

create table test_form_entity_multi_select_aud (
    rev integer not null,
    test_form_id bigint not null,
    entity_multi_select_id bigint not null,
    revtype smallint,
    primary key (rev, test_form_id, entity_multi_select_id));

create table test_form_file_input_aud (
    rev integer not null,
    test_form_id bigint not null,
    file_input_id bigint not null,
    revtype smallint,
    primary key (rev, test_form_id, file_input_id));

create table test_form (
    id bigint generated by default as identity,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    checkbox boolean,
    checkbox_picker boolean,
    checkbox_toggle boolean,
    date timestamp,
    date_time timestamp,
    summernote varchar(32000),
    text_area varchar(32000),
    text_field varchar(255),
    entity_select_id bigint,
    preloaded_entity_select_id bigint,
    primary key (id));

create table test_form_entity_multi_select (
    test_form_id bigint not null,
    entity_multi_select_id bigint not null);

create table test_form_file_input (
    test_form_id bigint not null,
    file_input_id bigint not null,
    primary key (test_form_id, file_input_id));

create table user_dashboard_aud (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    form_url_encoded_body varchar(255),
    name varchar(255),
    primary key (id, rev));

create table user_dashboard_users_aud (
    rev integer not null,
    dashboards_id bigint not null,
    users_id bigint not null,
    revtype smallint,
    primary key (rev, dashboards_id, users_id));

create table user_dashboard (
    id bigint generated by default as identity,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    form_url_encoded_body varchar(255) not null,
    name varchar(255) not null,
    primary key (id));

create table user_dashboard_users (
    dashboards_id bigint not null,
    users_id bigint not null,
    primary key (dashboards_id, users_id));

create table vietnam_import_source_files_aud (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    description varchar(255),
    name varchar(255),
    primary key (id, rev));

create table vietnam_import_source_files_city_department_group_file_aud (
    rev integer not null,
    vietnam_import_source_files_id bigint not null,
    city_department_group_file_id bigint not null,
    revtype smallint,
    primary key (rev, vietnam_import_source_files_id, city_department_group_file_id));

create table vietnam_import_source_files_locations_file_aud (
    rev integer not null,
    vietnam_import_source_files_id bigint not null,
    locations_file_id bigint not null,
    revtype smallint,
    primary key (rev, vietnam_import_source_files_id, locations_file_id));

create table vietnam_import_source_files_prototype_database_file_aud (
    rev integer not null,
    vietnam_import_source_files_id bigint not null,
    prototype_database_file_id bigint not null,
    revtype smallint,
    primary key (rev, vietnam_import_source_files_id, prototype_database_file_id));

create table vietnam_import_source_files_public_institutions_suppliers_file_aud (
    rev integer not null,
    vietnam_import_source_files_id bigint not null,
    public_institutions_suppliers_file_id bigint not null,
    revtype smallint,
    primary key (rev, vietnam_import_source_files_id, public_institutions_suppliers_file_id));

create table vietnam_import_source_files (
    id bigint generated by default as identity,
    created timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    last_updated timestamp,
    description varchar(255),
    name varchar(255),
    primary key (id));

create table vietnam_import_source_files_city_department_group_file (
    vietnam_import_source_files_id bigint not null,
    city_department_group_file_id bigint not null,
    primary key (vietnam_import_source_files_id, city_department_group_file_id));

create table vietnam_import_source_files_locations_file (
    vietnam_import_source_files_id bigint not null,
    locations_file_id bigint not null,
    primary key (vietnam_import_source_files_id, locations_file_id));

create table vietnam_import_source_files_prototype_database_file (
    vietnam_import_source_files_id bigint not null,
    prototype_database_file_id bigint not null,
    primary key (vietnam_import_source_files_id, prototype_database_file_id));

create table vietnam_import_source_files_public_institutions_suppliers_file (
    vietnam_import_source_files_id bigint not null,
    public_institutions_suppliers_file_id bigint not null,
    primary key (vietnam_import_source_files_id, public_institutions_suppliers_file_id));


create index IDXqa4k6p9mhd8aa4xc39uygxwut on category (label);

create index IDXoqu1m3l2e1r6ohx7l7xnshf5l on category (dtype);

alter table test_form_file_input
  add constraint UK_3s6o9w6gxuohwst9jo2icdvir unique (file_input_id);

create index IDXg6wwyfhbq0e0m0kii6hrfjnjk on vietnam_import_source_files (name);

alter table vietnam_import_source_files_city_department_group_file
  add constraint UK_t3mii96uvd5xrksmkn1vqwhon unique (city_department_group_file_id);

alter table vietnam_import_source_files_locations_file
  add constraint UK_sm3o40kbd3cqv9gyvfma51xhb unique (locations_file_id);

alter table vietnam_import_source_files_prototype_database_file
  add constraint UK_15b0820p0n86f6kgcgya517v4 unique (prototype_database_file_id);

alter table vietnam_import_source_files_public_institutions_suppliers_file
  add constraint UK_8u1q77mc9prfxk9524bwe283u unique (public_institutions_suppliers_file_id);

alter table admin_settings_aud
  add constraint FKcsgqjj3ubd6axhcyrhyud1d2d foreign key (rev) references revinfo;

alter table category_aud
  add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;

alter table file_metadata_aud
  add constraint FK4c7sqmts0bd2ksjplf9xk5gdg foreign key (rev) references revinfo;

alter table file_metadata
  add constraint FK1vmcjdfnkg2al2ygqlyrfy34 foreign key (content_id) references file_content;

alter table person
  add constraint FK8dsa4x1u4tnsxpfufcf4gj0gv foreign key (default_dashboard_id) references user_dashboard;

alter table person
  add constraint FK1uixneokc3sptbn98emoctx1 foreign key (group_id) references category;

alter table person_aud
  add constraint FK9lyxk62ui3cyr5k0w8etnfqkm foreign key (rev) references revinfo;

alter table person_roles
  add constraint FK7s0o6k42r2stk8tc0qk2r5t4i foreign key (roles_id) references role;

alter table person_roles
  add constraint FKs955luj19xyjwi3s1omo1pgh4 foreign key (person_id) references person;

alter table person_roles_aud
  add constraint FK13wlr36x8e4lq06ncgbdhttuo foreign key (rev) references revinfo;

alter table role_aud
  add constraint FKrks7qtsmup3w81fdp0d6omfk7 foreign key (rev) references revinfo;

alter table test_form_aud
  add constraint FK6sc8mtqj6a8a3vjkoc23ykgcy foreign key (rev) references revinfo;

alter table test_form_entity_multi_select_aud
  add constraint FKhdjgbv6ukclaq4sjnb8nnd36d foreign key (rev) references revinfo;

alter table test_form_file_input_aud
  add constraint FK9bhbx5b3b194fbyfj5l0hvxxf foreign key (rev) references revinfo;

alter table test_form
  add constraint FK3puknyft1wn7auw4i3hlexj1u foreign key (entity_select_id) references category;

alter table test_form
  add constraint FKdmeiuxo5oa2s6pfh6vev0pind foreign key (preloaded_entity_select_id) references category;

alter table test_form_entity_multi_select
  add constraint FKowfdrvs5b7mva7r4oo0aabf4r foreign key (entity_multi_select_id) references role;

alter table test_form_entity_multi_select
  add constraint FKe989278rqrn9r6ranjq5tsrhs foreign key (test_form_id) references test_form;

alter table test_form_file_input
  add constraint FKdldh5ome7s40dd4l71riknu8j foreign key (file_input_id) references file_metadata;

alter table test_form_file_input
  add constraint FKsdbk55p19hqk2caogjmswajak foreign key (test_form_id) references test_form;

alter table user_dashboard_aud
  add constraint FKdx16xod1mo3vr4vsmbdps40mb foreign key (rev) references revinfo;

alter table user_dashboard_users_aud
  add constraint FKt0ukopja39g0ng19i2tb8c9xq foreign key (rev) references revinfo;

alter table user_dashboard_users
  add constraint FK71lbntjpbrggymdiu3jptqcpc foreign key (users_id) references person;

alter table user_dashboard_users
  add constraint FKawgg95t7hhhvecmrewlj3qg8g foreign key (dashboards_id) references user_dashboard;

alter table vietnam_import_source_files_aud
  add constraint FKiefi5l6nki5iio9avua09x592 foreign key (rev) references revinfo;

alter table vietnam_import_source_files_city_department_group_file_aud
  add constraint FKkoitqesyhrgd8h0ocitrd6pee foreign key (rev) references revinfo;

alter table vietnam_import_source_files_locations_file_aud
  add constraint FKly2ntrlulwgbf47k61ebqm8wv foreign key (rev) references revinfo;

alter table vietnam_import_source_files_prototype_database_file_aud
  add constraint FK8nmafxlgbqf9s4qokyneyp58k foreign key (rev) references revinfo;

alter table vietnam_import_source_files_public_institutions_suppliers_file_aud
  add constraint FK8xd1n9rtq8yips5f9haee4dhb foreign key (rev) references revinfo;

alter table vietnam_import_source_files_city_department_group_file
  add constraint FKfj8ob5ihry7y5voj2i8u6g0gd foreign key (city_department_group_file_id) references file_metadata;

alter table vietnam_import_source_files_city_department_group_file
  add constraint FKle7f55weu4nkcqa67ekyyxby5 foreign key (vietnam_import_source_files_id) references vietnam_import_source_files;

alter table vietnam_import_source_files_locations_file
  add constraint FK4tp3rldkoubwe2icfxs6ouvqj foreign key (locations_file_id) references file_metadata;

alter table vietnam_import_source_files_locations_file
  add constraint FKjdj3duiul1xxyugdhqopct995 foreign key (vietnam_import_source_files_id) references vietnam_import_source_files;

alter table vietnam_import_source_files_prototype_database_file
  add constraint FKqqsaykseguaei0smol3v9go34 foreign key (prototype_database_file_id) references file_metadata;

alter table vietnam_import_source_files_prototype_database_file
  add constraint FK1m44ao56kbf4pvui270q3c39j foreign key (vietnam_import_source_files_id) references vietnam_import_source_files;

alter table vietnam_import_source_files_public_institutions_suppliers_file
  add constraint FKnr9gbmqpehaw4d3olgr44qw26 foreign key (public_institutions_suppliers_file_id) references file_metadata;

alter table vietnam_import_source_files_public_institutions_suppliers_file
  add constraint FK1vxr8hq1if6e5k93esfe0nhwd foreign key (vietnam_import_source_files_id) references vietnam_import_source_files;