create table ACTIVITY (
	id bigint generated by default as identity,
	primary key (id));

create table ACTIVITY_DERIVED (
	activity_id bigint not null,
	favourites_count bigint,
	ratings_avg double,
	ratings_count bigint,
	ratings_sum bigint,
	primary key (activity_id));

create table ACTIVITY_PROPERTIES (
	id bigint generated by default as identity,
	age_max integer check (age_max<=100),
	age_min integer check (age_min<=100),
	date_created timestamp,
	date_published timestamp,
	date_updated timestamp,
	description_introduction varchar(20000),
	description_main varchar(20000),
	description_material varchar(20000),
	description_notes varchar(20000),
	description_prepare varchar(20000),
	description_safety varchar(20000),
	featured boolean,
	name varchar(100),
	participants_max integer,
	participants_min integer,
	source varchar(255),
	time_max integer,
	time_min integer,
	activity_id bigint not null,
	author_id bigint,
	publishing_activity_id bigint,
	primary key (id));

create table ACTIVITY_PROPERTIES_MEDIA_FILE (
	activity_properties_id bigint not null,
	media_file_id bigint not null,
	featured boolean not null,
	primary key (activity_properties_id, media_file_id));

create table ACTIVITY_PROPERTIES_TAG (
	activity_properties_id bigint not null,
	tag_id bigint not null,
	primary key (activity_properties_id, tag_id));

create table ACTIVITY_RATING (
	activity_id bigint not null,
	user_id bigint not null,
	favourite boolean not null,
	rating integer,
	primary key (activity_id, user_id));

create table ACTIVITY_RELATION (
  activity_1_id bigint not null,
  activity_2_id bigint not null,
  owner_id bigint not null,
  primary key (activity_1_id, activity_2_id));

create table MEDIA_FILE (
  id bigint generated by default as identity,
  author varchar(50),
  capture_date timestamp,
  copy_right varchar(100),
  mime_type varchar(255),
  name varchar(100),
  uri varchar(255) not null,
  primary key (id));

create table MEDIA_FILE_KEYWORDS (
  MEDIA_FILE_ID bigint not null,
  KEYWORD varchar(100));

create table SYSTEM_MESSAGE (
  id bigint generated by default as identity,
  key varchar(255) not null,
  valid_from timestamp,
  valid_to timestamp,
  value varchar(255) not null,
  primary key (id));


create table tag (
  id bigint generated by default as identity,
  grp varchar(255) not null,
  name varchar(255) not null,
  media_file_id bigint,
  primary key (id));

create table TAG_DERIVED (
  tag_id bigint not null,
  activities_count bigint,
  primary key (tag_id));

create table user_identity (
  id bigint generated by default as identity,
  date_created timestamp,
  type varchar(255) not null,
  value varchar(255) not null,
  user_id bigint,
  primary key (id));


create table USERS (
  id bigint generated by default as identity,
  authorization_level integer not null,
  date_created timestamp,
  email_address varchar(255),
  name varchar(255) not null,
  primary key (id));

alter table ACTIVITY_PROPERTIES
  add constraint UK_8p7loosny10awv82317dn44t4 unique (publishing_activity_id);

alter table MEDIA_FILE
  add constraint UK_3u9rulgy7yjomvqsjry03822 unique (uri);

alter table SYSTEM_MESSAGE
  add constraint UK_croety7a27ejehvinhmotduqi unique (key);

alter table ACTIVITY_DERIVED
  add constraint FKo8u7ax9qdq62sfrxonti47f1o foreign key (activity_id) references ACTIVITY;

alter table ACTIVITY_PROPERTIES
  add constraint FKjio5ieiaen1roh8u271cdtfen foreign key (activity_id) references ACTIVITY;

alter table ACTIVITY_PROPERTIES
  add constraint FKb2iwkw3h9uy26io0h18ytin7s foreign key (author_id) references USERS;

alter table ACTIVITY_PROPERTIES
  add constraint FKp3x4u4f0skq9280prh1apwaoo foreign key (publishing_activity_id) references ACTIVITY;

alter table ACTIVITY_PROPERTIES_MEDIA_FILE
  add constraint FKhnjlvy0ssyabqgt90iak27iwk foreign key (activity_properties_id) references ACTIVITY_PROPERTIES;

alter table ACTIVITY_PROPERTIES_MEDIA_FILE
  add constraint FKpibj0h5moxdff7gasguqdlxwm foreign key (media_file_id) references MEDIA_FILE;

alter table ACTIVITY_PROPERTIES_TAG
  add constraint FKfcnl6h4ndsmypae8g3i2mlpn foreign key (activity_properties_id) references ACTIVITY_PROPERTIES;

alter table ACTIVITY_PROPERTIES_TAG
  add constraint FKcyehhnsd0gg0atto3wlbgl0tr foreign key (tag_id) references tag;

alter table ACTIVITY_RATING
  add constraint FKk3wxka6u3bbsd3gwkp2dac58e foreign key (activity_id) references ACTIVITY;

alter table ACTIVITY_RATING
  add constraint FKhdmqsgb6jm8vm24iucmw9mdy6 foreign key (user_id) references USERS;

alter table ACTIVITY_RELATION
  add constraint FKqxw4os0e4bf1656gh7ao30r09 foreign key (activity_1_id) references ACTIVITY;

alter table ACTIVITY_RELATION
  add constraint FK9kdvtwk9dgdgb9bjmi9i9nt1v foreign key (activity_2_id) references ACTIVITY;

alter table ACTIVITY_RELATION
  add constraint FK8rgoa19x05i5tv7uwx7be91r7 foreign key (owner_id) references USERS;

alter table MEDIA_FILE_KEYWORDS
  add constraint FKs8jjmwarvb02bue5i9sfe85pj foreign key (MEDIA_FILE_ID) references MEDIA_FILE;

alter table tag
  add constraint FKsb08vyx2itsgsetoyxmwia9ef foreign key (media_file_id) references MEDIA_FILE;

alter table TAG_DERIVED
  add constraint FKeec8pvit9s2w3bvj0nh1a7m4s foreign key (tag_id) references tag;

alter table user_identity
  add constraint FK7ef0ga5uu63bydc7uapmy8p4u foreign key (user_id) references USERS;
