/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.example.real.thrift.test;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.15.0)", date = "2021-11-12")
public class OptionalSetDefaultTest implements org.apache.thrift.TBase<OptionalSetDefaultTest, OptionalSetDefaultTest._Fields>, java.io.Serializable, Cloneable, Comparable<OptionalSetDefaultTest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("OptionalSetDefaultTest");

  private static final org.apache.thrift.protocol.TField WITH_DEFAULT_FIELD_DESC = new org.apache.thrift.protocol.TField("with_default", org.apache.thrift.protocol.TType.SET, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new OptionalSetDefaultTestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new OptionalSetDefaultTestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.Set<java.lang.String> with_default; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    WITH_DEFAULT((short)1, "with_default");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // WITH_DEFAULT
          return WITH_DEFAULT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.WITH_DEFAULT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.WITH_DEFAULT, new org.apache.thrift.meta_data.FieldMetaData("with_default", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(OptionalSetDefaultTest.class, metaDataMap);
  }

  public OptionalSetDefaultTest() {
    this.with_default = new java.util.HashSet<java.lang.String>();
    this.with_default.add("test");

  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public OptionalSetDefaultTest(OptionalSetDefaultTest other) {
    if (other.isSetWith_default()) {
      java.util.Set<java.lang.String> __this__with_default = new java.util.HashSet<java.lang.String>(other.with_default);
      this.with_default = __this__with_default;
    }
  }

  public OptionalSetDefaultTest deepCopy() {
    return new OptionalSetDefaultTest(this);
  }

  @Override
  public void clear() {
    this.with_default = new java.util.HashSet<java.lang.String>();
    this.with_default.add("test");

  }

  public int getWith_defaultSize() {
    return (this.with_default == null) ? 0 : this.with_default.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getWith_defaultIterator() {
    return (this.with_default == null) ? null : this.with_default.iterator();
  }

  public void addToWith_default(java.lang.String elem) {
    if (this.with_default == null) {
      this.with_default = new java.util.HashSet<java.lang.String>();
    }
    this.with_default.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Set<java.lang.String> getWith_default() {
    return this.with_default;
  }

  public OptionalSetDefaultTest setWith_default(@org.apache.thrift.annotation.Nullable java.util.Set<java.lang.String> with_default) {
    this.with_default = with_default;
    return this;
  }

  public void unsetWith_default() {
    this.with_default = null;
  }

  /** Returns true if field with_default is set (has been assigned a value) and false otherwise */
  public boolean isSetWith_default() {
    return this.with_default != null;
  }

  public void setWith_defaultIsSet(boolean value) {
    if (!value) {
      this.with_default = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case WITH_DEFAULT:
      if (value == null) {
        unsetWith_default();
      } else {
        setWith_default((java.util.Set<java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case WITH_DEFAULT:
      return getWith_default();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case WITH_DEFAULT:
      return isSetWith_default();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof OptionalSetDefaultTest)
      return this.equals((OptionalSetDefaultTest)that);
    return false;
  }

  public boolean equals(OptionalSetDefaultTest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_with_default = true && this.isSetWith_default();
    boolean that_present_with_default = true && that.isSetWith_default();
    if (this_present_with_default || that_present_with_default) {
      if (!(this_present_with_default && that_present_with_default))
        return false;
      if (!this.with_default.equals(that.with_default))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetWith_default()) ? 131071 : 524287);
    if (isSetWith_default())
      hashCode = hashCode * 8191 + with_default.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(OptionalSetDefaultTest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetWith_default(), other.isSetWith_default());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWith_default()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.with_default, other.with_default);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("OptionalSetDefaultTest(");
    boolean first = true;

    if (isSetWith_default()) {
      sb.append("with_default:");
      if (this.with_default == null) {
        sb.append("null");
      } else {
        sb.append(this.with_default);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class OptionalSetDefaultTestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public OptionalSetDefaultTestStandardScheme getScheme() {
      return new OptionalSetDefaultTestStandardScheme();
    }
  }

  private static class OptionalSetDefaultTestStandardScheme extends org.apache.thrift.scheme.StandardScheme<OptionalSetDefaultTest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, OptionalSetDefaultTest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // WITH_DEFAULT
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set298 = iprot.readSetBegin();
                struct.with_default = new java.util.HashSet<java.lang.String>(2*_set298.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem299;
                for (int _i300 = 0; _i300 < _set298.size; ++_i300)
                {
                  _elem299 = iprot.readString();
                  struct.with_default.add(_elem299);
                }
                iprot.readSetEnd();
              }
              struct.setWith_defaultIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, OptionalSetDefaultTest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.with_default != null) {
        if (struct.isSetWith_default()) {
          oprot.writeFieldBegin(WITH_DEFAULT_FIELD_DESC);
          {
            oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, struct.with_default.size()));
            for (java.lang.String _iter301 : struct.with_default)
            {
              oprot.writeString(_iter301);
            }
            oprot.writeSetEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class OptionalSetDefaultTestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public OptionalSetDefaultTestTupleScheme getScheme() {
      return new OptionalSetDefaultTestTupleScheme();
    }
  }

  private static class OptionalSetDefaultTestTupleScheme extends org.apache.thrift.scheme.TupleScheme<OptionalSetDefaultTest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, OptionalSetDefaultTest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetWith_default()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetWith_default()) {
        {
          oprot.writeI32(struct.with_default.size());
          for (java.lang.String _iter302 : struct.with_default)
          {
            oprot.writeString(_iter302);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, OptionalSetDefaultTest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TSet _set303 = iprot.readSetBegin(org.apache.thrift.protocol.TType.STRING);
          struct.with_default = new java.util.HashSet<java.lang.String>(2*_set303.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem304;
          for (int _i305 = 0; _i305 < _set303.size; ++_i305)
          {
            _elem304 = iprot.readString();
            struct.with_default.add(_elem304);
          }
        }
        struct.setWith_defaultIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

