import org.evomaster.client.java.controller.api.dto.database.schema.DbSchemaDto;
import org.evomaster.client.java.sql.SchemaExtractor;
import org.evomaster.client.java.sql.SqlScriptRunner;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;
import org.testcontainers.shaded.org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.Instant;

import static org.junit.Assert.assertEquals;

public class DbConstraintSolverTest {

    static String resourcesFolder = System.getProperty("user.dir") + "/src/test/resources/";
    private static Connection connection;
    private static DbConstraintSolver dbConstraintSolver;

    @BeforeAll
    static void setup() throws Exception {

        connection = DriverManager.getConnection("jdbc:h2:mem:constraint_test", "sa", "");

        SqlScriptRunner.execCommand(connection, "CREATE TABLE users(id bigint generated by default as identity primary key, name varchar(255), age int, points int);\n" +
                "ALTER TABLE users add CHECK (age>18 AND age<100);\n" +
                "ALTER TABLE users add CHECK (points<=10);\n" +
                "ALTER TABLE users add CHECK (points>=0);");

        DbSchemaDto schemaDto = SchemaExtractor.extract(connection);
        dbConstraintSolver = new DbConstraintSolver(schemaDto, resourcesFolder);
    }

    @AfterAll
    static void tearDown() throws SQLException, IOException {
        connection.close();
        dbConstraintSolver.close();
    }

    @Test
    public void testSolve() {
        String sqlQuery = "SELECT * FROM users WHERE age = 20 AND points = 5";
        String result = dbConstraintSolver.solve(sqlQuery);
        assertEquals("sat\n" +
                "((users1 (id-name-age-points 2 \"!0!\" 20 5)))\n" +
                "((users2 (id-name-age-points 3 \"!1!\" 20 5)))\n", result);
    }
}