package org.evomaster.clientJava.controllerApi.dto.database.operations;

public class InsertionEntryDto {

    public String variableName;

    public String printableValue;

    /**
     * If non null, then printableValue should be null.
     * This should be an id of an InsertionDto previously
     * executed
     */
    public Long foreignKeyToPreviouslyGeneratedRow;

    /**
     * Indicates if the current column is a primary
     * key that is a foreign key to a autoIncrement
     * column (transitively).
     */
    public Boolean keepAutoGeneratedValue;

}
