[[auth]]
name="logintoken"
[auth.loginEndpointAuth]
endpoint="/api/logintoken/login"
payloadRaw= """
{"userId": "userName1", "password":"password1234"}
"""
verb="POST"
contentType="application/json"
[auth.loginEndpointAuth.token]
headerPrefix="Bearer "
extractFromField = "/token/authToken"
httpHeaderName="Authorization"
