package org.evomaster.core.problem.asyncapi.service

import com.google.inject.Injector
import com.google.inject.Key
import com.google.inject.TypeLiteral
import com.webfuzzing.asyncapi.access.AsyncApiAccess
import org.evomaster.client.java.controller.api.dto.SutInfoDto
import org.evomaster.client.java.controller.api.dto.problem.asyncapi.AsyncApiActionDto
import org.evomaster.client.java.controller.api.dto.problem.asyncapi.AsyncApiReplyDto
import org.evomaster.core.output.TestCase
import org.evomaster.core.output.Lines
import org.evomaster.core.output.OutputFormat
import org.evomaster.core.output.Termination
import org.evomaster.core.output.service.KafkaTestClientEmitter
import org.evomaster.core.search.Solution
import org.evomaster.core.EMConfig
import org.evomaster.core.output.service.TestSuiteWriter
import org.evomaster.core.output.service.TestCaseWriter
import org.evomaster.core.problem.asyncapi.data.AsyncApiAction
import org.evomaster.core.problem.asyncapi.data.AsyncApiIndividual
import org.evomaster.core.problem.enterprise.SampleType
import org.evomaster.core.problem.rest.builder.RestActionBuilderV3
import org.evomaster.core.search.EvaluatedIndividual
import org.evomaster.core.search.service.FitnessFunction
import org.evomaster.core.search.service.Randomness
import org.evomaster.core.search.service.SearchGlobalState
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Assumptions
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

/**
 * What a generated test looks like. The lines that publish are the driver's, so the fake one
 * renders a stand-in for them here, exactly as a Kafka driver would render a producer.
 */
class AsyncApiTestCaseWriterTest {

    companion object {
        private const val DOUBLE_RESULT = """{"resultAsDouble": 1.5}"""

        /**
         * Every line any other suite opens with, taken verbatim from what the writer produces
         * for a suite with no tests in it (see TestSuiteWriterTest). The class name and the
         * driver's own name are left out, as those are all that may differ.
         */
        private val SCAFFOLDING_EVERY_SUITE_HAS = listOf(
            "/**",
            "* LICENSE DISCLAIMER",
            "* This file has been generated by EvoMaster.",
            "* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.",
            "* This generated software (i.e., the test suite in this file) can be freely used, modified,",
            "* and distributed as you see fit without any restrictions.",
            "*/",
            "import  org.junit.jupiter.api.AfterAll",
            "import  org.junit.jupiter.api.BeforeAll",
            "import  org.junit.jupiter.api.BeforeEach",
            "import  org.junit.jupiter.api.Test",
            "import  org.junit.jupiter.api.Timeout",
            "import  org.junit.jupiter.api.Assertions.*",
            "import  java.util.List",
            "import  org.evomaster.test.utils.EMTestUtils.*",
            "import  org.evomaster.client.java.controller.SutHandler",
            "import  java.math.BigDecimal",
            "import  java.math.BigInteger",
            "import  org.hamcrest.Matchers",
            "import  org.hamcrest.Matchers.*",
            "import  org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*",
            "import  org.evomaster.client.java.controller.contentMatchers.StringMatcher.*",
            "import  org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*",
            "    companion object {",
            "        private lateinit var baseUrlOfSut: String",
            "        @BeforeAll",
            "        @JvmStatic",
            "        fun initClass() {",
            "            controller.setupForGeneratedTest()",
            "            baseUrlOfSut = controller.startSut()",
            "            controller.registerOrExecuteInitSqlCommandsIfNeeded()",
            "            assertNotNull(baseUrlOfSut)",
            "        }",
            "        @AfterAll",
            "        @JvmStatic",
            "        fun tearDown() {",
            "            controller.stopSut()",
            "        }",
            "    }",
            "    @BeforeEach",
            "    fun initTest() {",
            "        controller.resetStateOfSUT()",
            "    }"
        )

        /**
         * What a driver hands over: lines that stand up a client, publish, and read the reply
         * into a variable it names.
         */
        private fun withScript(payload: String, dto: AsyncApiActionDto): AsyncApiReplyDto =
            FakeAsyncApiDriver.replied(payload).apply {
                //named off the variable the core supplied, which is unique per action
                val v = dto.replyVariable
                testScript = listOf(
                    "val producer_$v = connectProducer(\"localhost:9092\")",
                    "producer_$v.send(recordFor(\"${dto.address}\"))",
                    "val $v = pollUntilCorrelated(\"${dto.replyAddress}\")"
                )
            }
    }

    private lateinit var injector: Injector
    private lateinit var driver: FakeAsyncApiDriver
    private lateinit var sampler: AsyncApiSampler
    private lateinit var fitness: FitnessFunction<AsyncApiIndividual>

    @BeforeEach
    fun reset() {
        RestActionBuilderV3.cleanCache()
    }

    private fun start(answer: (AsyncApiActionDto) -> AsyncApiReplyDto?) {
        driver = FakeAsyncApiDriver(AsyncApiTestInjector.sutInfo(AsyncApiAccess.readFromResource(AsyncApiTestInjector.NCS)), answer)
        injector = AsyncApiTestInjector.create(
            driver,
            "--blackBox=false",
            //the core only asks a driver to render lines when a test will be written
            "--createTests=true",
            "--outputFormat=KOTLIN_JUNIT_5"
        )
        sampler = injector.getInstance(AsyncApiSampler::class.java)
        fitness = injector.getInstance(Key.get(object : TypeLiteral<FitnessFunction<AsyncApiIndividual>>() {}))
    }

    private fun evaluate(vararg names: String): EvaluatedIndividual<AsyncApiIndividual> {
        val randomness = injector.getInstance(Randomness::class.java)
        val actions = names.map { name ->
            val template = sampler.seeAvailableActions().first { it.getName() == name }
            (template.copy() as AsyncApiAction).apply { doInitialize(randomness) }
        }
        val individual = AsyncApiIndividual(SampleType.RANDOM, actions.toMutableList()).apply {
            doGlobalInitialize(injector.getInstance(SearchGlobalState::class.java))
        }
        return fitness.calculateCoverage(individual, modifiedSpec = null)
            ?: fail("the fitness gave up on the individual")
    }

    /**
     * The members the writer adds to the test class for a solution holding this one test.
     */
    private fun membersOf(evaluated: EvaluatedIndividual<AsyncApiIndividual>): String {
        val writer = injector.getInstance(TestCaseWriter::class.java)
        val solution = Solution(mutableListOf(evaluated), "Prefix", "Suffix", Termination.NONE, listOf(), listOf())
        val lines = Lines(injector.getInstance(EMConfig::class.java).outputFormat)
        writer.addExtraClassMembers(lines, solution)
        return lines.toString()
    }

    /**
     * The generated body for one test, as the suite writer would ask for it.
     */
    private fun bodyOf(evaluated: EvaluatedIndividual<AsyncApiIndividual>): String {
        val writer = injector.getInstance(TestCaseWriter::class.java)
        return writer.convertToCompilableTestCode(TestCase(evaluated, "test_0"), "baseUrlOfSut").toString()
    }

    @Test
    fun testTheDriversLinesAreWhatPublishes() {

        start { withScript(DOUBLE_RESULT, it) }

        val body = bodyOf(evaluate("bessj"))

        //the driver's own client code, pasted as it was rendered
        assertTrue(body.contains("connectProducer(\"localhost:9092\")"), body)
        assertTrue(body.contains("pollUntilCorrelated"), body)

        //and what only the core knows about the reply
        assertTrue(body.contains("assertNotNull(res_0)"), body)
        assertTrue(body.contains("bessj: REPLIED"), body)
    }

    @Test
    fun testEachActionKeepsItsOwnLines() {

        start { withScript(DOUBLE_RESULT, it) }

        val body = bodyOf(evaluate("bessj", "expint"))

        //the core names the variables, so two actions in one test cannot collide
        assertTrue(body.contains("assertNotNull(res_0)"), body)
        assertTrue(body.contains("assertNotNull(res_1)"), body)
        assertTrue(body.contains("producer_res_0"), body)
        assertTrue(body.contains("producer_res_1"), body)
    }

    @Test
    fun testTheDriverIsToldWhichLanguageToRenderAndWhereToLeaveTheReply() {

        start { withScript(DOUBLE_RESULT, it) }
        evaluate("bessj")

        val asked = driver.published.single()
        assertEquals(SutInfoDto.OutputFormat.KOTLIN_JUNIT_5, asked.outputFormat)
        assertEquals("res_0", asked.replyVariable)
    }

    @Test
    fun testKafkaIsWrittenFromTheContractWhenTheDriverRendersNothing() {

        /*
            The document names the broker, the topics and the header the correlation id rides in,
            so the test can publish with an ordinary client and no driver has to render anything.
         */
        start { FakeAsyncApiDriver.replied(DOUBLE_RESULT) }

        val evaluated = evaluate("bessj")

        /*
            The members first, as the suite writer writes them: that is where the servers of a
            suite are learnt, and a body written before them would not know they exist.
         */
        val members = membersOf(evaluated)
        assertTrue(members.contains("KafkaProducer"), members)
        assertTrue(members.contains("KafkaConsumer"), members)
        //a reply older than the test is not an answer to it, and each run stamps its own id
        assertTrue(members.contains("seekToEnd"), members)
        assertTrue(members.contains("UUID.randomUUID()"), members)
        assertTrue(members.contains("asyncApiServer_kafka"), members)

        val body = bodyOf(evaluated)

        //one line per action: everything it needs came off the contract
        assertTrue(body.contains("${KafkaTestClientEmitter.HELPER_NAME}(asyncApiServer_kafka,"), body)
        assertTrue(body.contains("\"ncs.bessj.request\""), body)
        assertTrue(body.contains("\"ncs.bessj.reply\""), body)
        assertTrue(body.contains("\"correlationId\""), body)
        assertTrue(body.contains("assertNotNull(res_0)"), body)
        //the suite has a driver, so the document's address is not what a test publishes to
        assertFalse(body.contains("\"localhost:9092\""), body)
    }

    @Test
    fun testThePythonSuiteIsValidPython() {

        /*
            A Python suite has no driver to ask where the broker is, since the controller is
            Java, so it publishes to the address the document declares. What matters here is
            that what comes out parses: indentation is part of the language, so a helper written
            as text can break it in a way no JVM format can.
         */
        driver = FakeAsyncApiDriver(AsyncApiTestInjector.sutInfo(AsyncApiAccess.readFromResource(AsyncApiTestInjector.NCS))) {
            FakeAsyncApiDriver.replied(DOUBLE_RESULT)
        }
        injector = AsyncApiTestInjector.create(
            driver,
            //Python output is for black-box only, which is also why its suite has no driver to ask
            "--blackBox=true",
            "--createTests=true",
            "--outputFormat=PYTHON_UNITTEST"
        )
        sampler = injector.getInstance(AsyncApiSampler::class.java)
        fitness = injector.getInstance(Key.get(object : TypeLiteral<FitnessFunction<AsyncApiIndividual>>() {}))

        val evaluated = evaluate("bessj")
        val body = bodyOf(evaluated)
        val members = membersOf(evaluated)

        //the call, and the reply read as a dict rather than a tree of nodes
        assertTrue(body.contains("${KafkaTestClientEmitter.HELPER_NAME}("), body)
        assertTrue(body.contains("json.loads(res_0)"), body)
        assertTrue(body.contains("\"resultAsDouble\" in body_0"), body)
        assertTrue(body.contains("assert "), body)

        //and the helper it calls
        assertTrue(members.contains("kafka.KafkaProducer"), members)
        assertTrue(members.contains("seek_to_end"), members)

        /*
            Seeking to the end is lazy in every client written so far: without asking for the
            position, it takes effect on the first poll, by which time the reply is behind it and
            is never seen. A suite that only has to parse cannot catch that.
         */
        assertTrue(members.contains("consumer.position(partitions[0])"), members)

        //there is no driver in a Python suite, so nothing is declared to ask one
        assertFalse(members.contains(KafkaTestClientEmitter.SERVER_VARIABLE_PREFIX), members)
        assertFalse(body.contains(KafkaTestClientEmitter.SERVER_VARIABLE_PREFIX), body)

        //and the driver was asked for no script, as its own enum cannot name Python
        assertNull(driver.published.last().outputFormat)

        //what comes out has to be parseable Python, indentation included
        val module = (members.trimEnd().lines() + body.trimEnd().lines())
            .joinToString("\n") { "    " + it }
        val file = java.io.File.createTempFile("asyncapi_suite", ".py")
        file.writeText("import json\nimport time\nimport uuid\nimport kafka\n\n\nclass Suite:\n$module\n")

        try {
            val process = try {
                ProcessBuilder("python3", "-m", "py_compile", file.absolutePath)
                    .redirectErrorStream(true)
                    .start()
            } catch (e: java.io.IOException) {
                //no Python on this machine: the rest of the suite has nothing to do with one
                Assumptions.assumeTrue(false, "python3 is not on the PATH")
                return
            }
            val output = process.inputStream.bufferedReader().readText()
            val code = process.waitFor()

            assertEquals(0, code, "the generated Python does not parse:\n$output\n\n$module")
        } finally {
            file.delete()
        }
    }

    /**
     * A whole suite, written to disk by the shared suite writer and read back, which is the
     * only way to reach what it puts around the tests: the class, its lifecycle, and whether
     * there is a driver in it at all.
     */
    private fun writeSuite(extension: String, vararg options: String): String {

        val folder = java.nio.file.Files.createTempDirectory("asyncapi_suite").toFile()
        folder.deleteOnExit()

        driver = FakeAsyncApiDriver(AsyncApiTestInjector.sutInfo(AsyncApiAccess.readFromResource(AsyncApiTestInjector.NCS))) {
            FakeAsyncApiDriver.replied(DOUBLE_RESULT)
        }
        injector = AsyncApiTestInjector.create(driver, "--createTests=true", *options)
        sampler = injector.getInstance(AsyncApiSampler::class.java)
        fitness = injector.getInstance(Key.get(object : TypeLiteral<FitnessFunction<AsyncApiIndividual>>() {}))

        val config = injector.getInstance(EMConfig::class.java)
        config.outputFolder = folder.absolutePath
        config.outputFilePrefix = "AsyncApiSuite"
        config.outputFileSuffix = ""

        val evaluated = evaluate("bessj")
        val solution = Solution(mutableListOf(evaluated), "AsyncApiSuite", "", Termination.NONE, listOf(), listOf())

        injector.getInstance(TestSuiteWriter::class.java)
            .writeTests(solution, FakeAsyncApiDriver::class.qualifiedName!!, null)

        return folder.walkTopDown().first { it.isFile && it.name.endsWith(extension) }.readText()
    }

    @Test
    fun testABlackBoxSuiteHasNoDriverAndPublishesWhereTheDocumentSays() {

        /*
            Black-box is the mode this problem type is unusual in: a driver publishes while the
            search runs, because nothing else can, but the suite that run leaves behind has no
            driver in it. So there is nobody to ask where the broker is, and the only address
            there is is the one the document declares.
         */
        val written = writeSuite(".kt", "--blackBox=true", "--outputFormat=KOTLIN_JUNIT_5")

        //nothing of the driver: no field holding it, and nothing started or stopped
        assertFalse(written.contains("SutHandler = "), written)
        assertFalse(written.contains("controller.startSut()"), written)
        assertFalse(written.contains("controller.stopSut()"), written)
        assertFalse(written.contains("getAsyncApiServerAddress"), written)
        assertFalse(written.contains(KafkaTestClientEmitter.SERVER_VARIABLE_PREFIX), written)

        //and so the document's own address, as a literal, where the variable would have been
        assertTrue(
            written.contains("${KafkaTestClientEmitter.HELPER_NAME}(\"localhost:9092\", \"ncs.bessj.request\""),
            written
        )

        //the rest is what any other suite has
        assertTrue(written.contains("This file has been generated by EvoMaster"), written)
        assertTrue(written.contains("internal class AsyncApiSuite {"), written)
        assertTrue(written.contains("fun test_0_publishOnBessj"), written)
        assertTrue(written.contains("assertNotNull(res_0)"), written)
    }

    @Test
    fun testABlackBoxJavaSuiteFallsBackTheSameWay() {

        //the same, in the other language a JVM suite can be written in
        val written = writeSuite(".java", "--blackBox=true", "--outputFormat=JAVA_JUNIT_5")

        assertFalse(written.contains("SutHandler "), written)
        assertFalse(written.contains(KafkaTestClientEmitter.SERVER_VARIABLE_PREFIX), written)
        assertTrue(
            written.contains("${KafkaTestClientEmitter.HELPER_NAME}(\"localhost:9092\", \"ncs.bessj.request\""),
            written
        )
        assertTrue(written.contains("public class AsyncApiSuite {"), written)
    }

    @Test
    fun testTheWholeSuiteHasTheSameScaffoldingAsAnyOther() {

        /*
            The class, its lifecycle and the driver it starts come from the shared suite writer,
            so an AsyncAPI suite has to look like any other: only what a test does inside its own
            body is ours. Written to disk and read back, rather than asserted on fragments.
         */
        val folder = java.nio.file.Files.createTempDirectory("asyncapi_suite").toFile()
        folder.deleteOnExit()

        start { FakeAsyncApiDriver.replied(DOUBLE_RESULT) }

        val config = injector.getInstance(EMConfig::class.java)
        config.outputFolder = folder.absolutePath
        config.outputFilePrefix = "AsyncApiSuite"
        config.outputFileSuffix = ""

        val evaluated = evaluate("bessj")
        val solution = Solution(mutableListOf(evaluated), "AsyncApiSuite", "", Termination.NONE, listOf(), listOf())

        injector.getInstance(TestSuiteWriter::class.java)
            .writeTests(solution, FakeAsyncApiDriver::class.qualifiedName!!, null)

        val written = folder.walkTopDown().first { it.isFile && it.name.endsWith(".kt") }.readText()

        val actual = written.lines().map { it.trimEnd() }

        /*
            Every line another suite opens with has to be here, in the same order and with the
            same indentation. Extra lines in between are allowed: that is where what a suite of
            this problem type adds goes.
         */
        var from = 0
        SCAFFOLDING_EVERY_SUITE_HAS.forEach { line ->
            val at = actual.subList(from, actual.size).indexOf(line)
            assertTrue(at >= 0, "missing, or out of order: '" + line + "'\n\n" + written)
            from += at + 1
        }

        //the class and the driver it holds, which only differ by their names
        assertTrue(actual.contains("internal class AsyncApiSuite {"), written)
        assertTrue(actual.any { it.startsWith("        private val controller : SutHandler = ") }, written)

        //and ours on top of it, not instead of it
        assertTrue(written.contains("asyncApiServer_kafka = controller.getAsyncApiServerAddress"), written)
        assertTrue(written.contains("publishOnBessj"), written)

        folder.deleteRecursively()
    }

    @Test
    fun testTheDriverIsAskedForAnAddressOnlyOnce() {

        /*
            Java has no elvis, and the obvious ternary would name the call on both sides of it.
            A driver that works the address out, rather than keeping one, would then do that
            work twice every time a suite starts.
         */
        driver = FakeAsyncApiDriver(AsyncApiTestInjector.sutInfo(AsyncApiAccess.readFromResource(AsyncApiTestInjector.NCS))) {
            FakeAsyncApiDriver.replied(DOUBLE_RESULT)
        }
        injector = AsyncApiTestInjector.create(
            driver,
            "--blackBox=false",
            "--createTests=true",
            "--outputFormat=JAVA_JUNIT_5"
        )
        sampler = injector.getInstance(AsyncApiSampler::class.java)
        fitness = injector.getInstance(Key.get(object : TypeLiteral<FitnessFunction<AsyncApiIndividual>>() {}))

        val evaluated = evaluate("bessj")
        val writer = injector.getInstance(TestCaseWriter::class.java)
        val solution = Solution(mutableListOf(evaluated), "Prefix", "Suffix", Termination.NONE, listOf(), listOf())

        //declaring the members is what tells the writer which servers there are to ask about
        writer.addExtraClassMembers(Lines(OutputFormat.JAVA_JUNIT_5), solution)

        val lines = Lines(OutputFormat.JAVA_JUNIT_5)
        writer.addExtraInitStatement(lines)
        val init = lines.toString()

        assertEquals(1, init.split("getAsyncApiServerAddress").size - 1, init)

        assertEquals(
            "asyncApiServer_kafka = controller.getAsyncApiServerAddress(\"kafka\");\n" +
                    "if (asyncApiServer_kafka == null) {\n" +
                    "    asyncApiServer_kafka = \"localhost:9092\";\n" +
                    "}",
            init.trimEnd()
        )
    }

    @Test
    fun testTheKafkaHelperIsLeftOutWhenNothingCallsIt() {

        //a suite that never publishes over Kafka must not be made to carry the dependency
        start { FakeAsyncApiDriver.replied(DOUBLE_RESULT).apply { testScript = listOf("publishSomehow()") } }

        val members = membersOf(evaluate("bessj"))

        assertFalse(members.contains("KafkaProducer"), members)
    }

    @Test
    fun testATransportTheContractDoesNotDescribeSaysSoRatherThanWritingAnEmptyTest() {

        /*
            A socket carries its correlation id inside the service's own message layout, which the
            contract does not describe, so nothing here can write the client code. Only a driver
            can, and this one renders nothing.
         */
        val socket = """
            asyncapi: 3.0.0
            info:
              title: Socket
              version: 1.0.0
            servers:
              live:
                host: localhost:8080
                protocol: ws
            channels:
              requests:
                address: /requests
                servers:
                  - ${'$'}ref: '#/servers/live'
                messages:
                  request:
                    payload:
                      type: object
                      properties:
                        id:
                          type: string
            operations:
              ask:
                action: receive
                channel:
                  ${'$'}ref: '#/channels/requests'
        """.trimIndent()

        driver = FakeAsyncApiDriver(AsyncApiTestInjector.sutInfo(socket)) { FakeAsyncApiDriver.fireAndForget() }
        injector = AsyncApiTestInjector.create(
            driver,
            "--blackBox=false",
            "--createTests=true",
            "--outputFormat=KOTLIN_JUNIT_5"
        )
        sampler = injector.getInstance(AsyncApiSampler::class.java)
        fitness = injector.getInstance(Key.get(object : TypeLiteral<FitnessFunction<AsyncApiIndividual>>() {}))

        val body = bodyOf(evaluate("ask"))

        assertTrue(body.contains("not one"), body)
        assertTrue(body.contains("executeAsyncApiAction"), body)
        assertFalse(body.contains("KafkaProducer"), body)
    }

    @Test
    fun testAMessageThatWentUnansweredIsWrittenWithoutAReplyAssertion() {

        start {
            FakeAsyncApiDriver.silence().apply {
                testScript = listOf("publishAndWait()")
            }
        }

        val body = bodyOf(evaluate("bessj"))

        assertTrue(body.contains("publishAndWait()"), body)
        assertTrue(body.contains("NO_REPLY"), body)
        //nothing arrived, so there is nothing to assert on
        assertFalse(body.contains("assertNotNull"), body)
    }
}
