package org.evomaster.core.solver

import org.evomaster.client.java.controller.api.dto.database.schema.DbInfoDto
import org.evomaster.client.java.sql.DbInfoExtractor
import org.evomaster.client.java.sql.SqlScriptRunner
import org.evomaster.core.search.gene.BooleanGene
import org.evomaster.core.search.gene.Gene
import org.evomaster.core.search.gene.numeric.IntegerGene
import org.evomaster.core.search.gene.placeholder.ImmutableDataHolderGene
import org.evomaster.core.search.gene.sql.SqlPrimaryKeyGene
import org.evomaster.core.search.gene.string.StringGene
import org.evomaster.core.sql.SqlActionTransformer
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.DriverManager
import java.sql.SQLException


class SMTLibZ3DbConstraintSolverTest {

    companion object {
        private lateinit var solver: SMTLibZ3DbConstraintSolver
        private lateinit var connection: Connection
        private lateinit var schemaDto: DbInfoDto

        @JvmStatic
        @BeforeAll
        fun setup() {
            connection = DriverManager.getConnection("jdbc:h2:mem:constraint_test", "sa", "")
            SqlScriptRunner.execCommand(connection, "CREATE TABLE users(id bigint generated by default as identity primary key, name varchar(255), age int, points int, flag bit, created_at timestamp not null);\n")
            schemaDto = DbInfoExtractor.extract(connection)
            solver = SMTLibZ3DbConstraintSolver()
            solver.initializeExecutor()
        }

        @JvmStatic
        @AfterAll
        @Throws(SQLException::class)
        fun closeConnection() {
            connection.close()
            if (this::solver.isInitialized) {
                solver.close()
            }
        }
    }

    /**
     * Test the generation of SMT from a simple select statement and a database schema
     */
    @Test
    fun selectFromUsers() {

        val newActions = solver.solve(schemaDto, "SELECT * FROM Users WHERE name = 'agus';", 2)

        assertEquals(2, newActions.size)

        val genesInsert1: List<Gene> = newActions[0].seeTopGenes()

        assertEquals(6, genesInsert1.size)

        for (gene in genesInsert1) {
            when (gene.name) {
                "ID" -> {
                    assertTrue(gene is SqlPrimaryKeyGene)
                    val child = gene.getViewOfChildren().first()
                    assertEquals(5, (child as IntegerGene).value)
                }
                "NAME" -> {
                    assertTrue(gene is StringGene)
                    assertEquals("agus", (gene as StringGene).value)
                }
                "AGE" -> {
                    assertTrue(gene is IntegerGene)
                    assertEquals(6, (gene as IntegerGene).value)
                }
                "POINTS" -> {
                    assertTrue(gene is IntegerGene)
                    assertEquals(7, (gene as IntegerGene).value)
                }
                "FLAG" -> {
                    // H2 maps BIT to BOOLEAN, so the solver produces a BooleanGene
                    assertTrue(gene is BooleanGene)
                }
                "CREATED_AT" -> {
                    // TIMESTAMP epoch-seconds from Z3 are converted to a formatted datetime string
                    assertTrue(gene is ImmutableDataHolderGene)
                    val value = (gene as ImmutableDataHolderGene).value
                    assertTrue(value.matches(Regex("\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}")),
                        "Expected datetime format 'yyyy-MM-dd HH:mm:ss' but got: $value")
                }
                else -> {
                    fail("Unexpected gene: $gene")
                }
            }
        }

        val genesInsert2: List<Gene> = newActions[1].seeTopGenes()

        assertEquals(6, genesInsert2.size)

        for (gene in genesInsert2) {
            when (gene.name) {
                "ID" -> {
                    assertTrue(gene is SqlPrimaryKeyGene)
                    val child = gene.getViewOfChildren().first()
                    assertEquals(2, (child as IntegerGene).value)
                }
                "NAME" -> {
                    assertTrue(gene is StringGene)
                    assertEquals("agus", (gene as StringGene).value)
                }
                "AGE" -> {
                    assertTrue(gene is IntegerGene)
                    assertEquals(3, (gene as IntegerGene).value)
                }
                "POINTS" -> {
                    assertTrue(gene is IntegerGene)
                    assertEquals(4, (gene as IntegerGene).value)
                }
                "FLAG" -> {
                    // H2 maps BIT to BOOLEAN, so the solver produces a BooleanGene
                    assertTrue(gene is BooleanGene)
                }
                "CREATED_AT" -> {
                    // TIMESTAMP epoch-seconds from Z3 are converted to a formatted datetime string
                    assertTrue(gene is ImmutableDataHolderGene)
                    val value = (gene as ImmutableDataHolderGene).value
                    assertTrue(value.matches(Regex("\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}")),
                        "Expected datetime format 'yyyy-MM-dd HH:mm:ss' but got: $value")
                }
                else -> {
                    fail("Unexpected gene: $gene")
                }
            }
        }
    }

    /**
     * End-to-end test: verifies that the rows generated by the solver can be inserted
     * into the real database and that the original SELECT query then returns results.
     */
    @Test
    @Throws(SQLException::class)
    fun insertedRowsSatisfySelectQuery() {
        val selectQuery = "SELECT * FROM users WHERE age > 25"

        val actions = solver.solve(schemaDto, selectQuery, 2)
        assertFalse(actions.isEmpty(), "Solver should return actions for a satisfiable query")

        val dto = SqlActionTransformer.transform(actions)
        SqlScriptRunner.execInsert(connection, dto.insertions)

        val result = SqlScriptRunner.execCommand(connection, selectQuery)
        assertFalse(result.isEmpty(), "Inserted rows should satisfy the original SELECT query")
    }

    /**
     * Test the generation of SMT from a complicated cache local temporary table does not throw exception
     */
    @Test
    fun selectLocal() {

        val newActions = solver.solve(schemaDto, "create cached local temporary table if not exists HT_feature_constraint (id bigint not null) on commit drop transactional", 2)

        // This will be empty as the query does not correspond to the created database, just checking that it doesn't throw an exception
        assertEquals(0, newActions.size)
    }
}