package org.evomaster.core.solver

import org.evomaster.client.java.controller.api.dto.database.schema.DbInfoDto
import org.evomaster.client.java.sql.DbInfoExtractor
import org.evomaster.client.java.sql.SqlScriptRunner
import org.evomaster.core.EMConfig
import org.evomaster.core.search.service.Statistics
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.DriverManager
import org.evomaster.core.database.sql.solver.SMTLibZ3DbConstraintSolver

/**
 * Covers the memo of queries that cannot be translated.
 *
 * The solver's result cache deliberately stores only `SAT` and `UNSAT`: an `UNKNOWN` or an `ERROR`
 * from Z3 may be a timeout or a transient container fault, and caching one would turn a passing
 * problem into a permanent one. A *translation* failure is different in kind — the same SQL against
 * the same schema fails the same way every time — so remembering it is safe, and not remembering it
 * is expensive: the search keeps producing the same untranslatable queries, and each encounter pays
 * the parse and the generation attempt again.
 *
 * Note that a remembered failure is still counted in the statistics on every encounter, so the
 * reported failure totals keep reflecting how often the search runs into one.
 */
class UntranslatableQueryCacheTest {

    companion object {
        private lateinit var solver: SMTLibZ3DbConstraintSolver
        private lateinit var connection: Connection
        private lateinit var schemaDto: DbInfoDto

        /**
         * A second schema, identical but for one column of a type the generator does not map.
         *
         * It has to be a separate schema: table declarations are emitted for *every* table before any
         * query-specific work, so a single unmapped column makes generation fail for every query
         * against that schema, not only for queries touching the offending table.
         */
        private lateinit var schemaWithUnsupportedType: DbInfoDto
        private lateinit var unsupportedConnection: Connection

        /** Not valid SQL, so it fails in the parsing step. */
        private const val UNPARSEABLE = "this is not a SQL query at all"

        /**
         * Bound used by every test that is not about eviction. Comfortably above what any of them
         * stores, and small enough that none of this depends on the production default.
         */
        private const val CACHE_BOUND = 128

        /** Valid SQL, run against [schemaWithUnsupportedType] so it fails while generating SMT-LIB. */
        private const val UNSUPPORTED_TYPE = "SELECT * FROM blobs WHERE id = 1"

        @JvmStatic
        @BeforeAll
        fun setup() {
            connection = DriverManager.getConnection("jdbc:h2:mem:untranslatable_test", "sa", "")
            SqlScriptRunner.execCommand(
                connection,
                "CREATE TABLE users(id bigint generated by default as identity primary key, name varchar(255));\n"
            )
            schemaDto = DbInfoExtractor.extract(connection)

            unsupportedConnection =
                DriverManager.getConnection("jdbc:h2:mem:untranslatable_unsupported", "sa", "")
            SqlScriptRunner.execCommand(
                unsupportedConnection,
                "CREATE TABLE blobs(id bigint primary key, payload blob);\n"
            )
            schemaWithUnsupportedType = DbInfoExtractor.extract(unsupportedConnection)
            // No injector here, so the caches have to be allocated explicitly. The Z3 executor is
            // never reached: every query in this test fails before the solver would be invoked.
            solver = SMTLibZ3DbConstraintSolver()
            solver.initializeCaches(CACHE_BOUND)
        }

        @JvmStatic
        @AfterAll
        fun tearDown() {
            connection.close()
            unsupportedConnection.close()
        }
    }

    @BeforeEach
    fun freshCaches() {
        solver.initializeCaches(CACHE_BOUND)
    }

    @Test
    fun `an unparseable query is remembered after the first attempt`() {
        assertEquals(0, solver.untranslatableQueryCount())

        assertTrue(solver.solve(schemaDto, UNPARSEABLE, 1).isEmpty())

        assertEquals(1, solver.untranslatableQueryCount())
        assertTrue(solver.isRememberedUntranslatable(UNPARSEABLE, 1))
    }

    @Test
    fun `a query that fails while generating SMT-LIB is remembered too`() {
        assertTrue(solver.solve(schemaWithUnsupportedType, UNSUPPORTED_TYPE, 1).isEmpty())

        assertTrue(solver.isRememberedUntranslatable(UNSUPPORTED_TYPE, 1)) {
            "expected a generation failure to be remembered, not only a parse failure"
        }
    }

    @Test
    fun `repeated attempts keep returning empty and do not grow the memo`() {
        repeat(5) { assertTrue(solver.solve(schemaDto, UNPARSEABLE, 1).isEmpty()) }

        assertEquals(1, solver.untranslatableQueryCount()) {
            "the same query must occupy a single entry however often it is seen"
        }
    }

    /**
     * The row count is part of the key, matching the result cache. The same text at a different row
     * count is a different SMT-LIB problem, so it is tracked separately rather than assumed to fail
     * the same way.
     */
    @Test
    fun `the row count is part of the key`() {
        solver.solve(schemaDto, UNPARSEABLE, 1)

        assertTrue(solver.isRememberedUntranslatable(UNPARSEABLE, 1))
        assertFalse(solver.isRememberedUntranslatable(UNPARSEABLE, 2))

        solver.solve(schemaDto, UNPARSEABLE, 2)
        assertEquals(2, solver.untranslatableQueryCount())
    }

    /**
     * The memo records *which* step gave up, not merely that something did.
     *
     * This is what lets the reported failure totals be split into the two components that actually
     * need fixing — the SQL parser and the SMT-LIB generator — including on later encounters, which
     * are served from the memo and would otherwise have nothing to report.
     */
    @Test
    fun `the memo records which step failed`() {
        solver.solve(schemaDto, UNPARSEABLE, 1)
        solver.solve(schemaWithUnsupportedType, UNSUPPORTED_TYPE, 1)

        assertEquals(
            Statistics.SqlZ3TranslationFailure.SQL_PARSE,
            solver.rememberedFailureKind(UNPARSEABLE, 1)
        )
        assertEquals(
            Statistics.SqlZ3TranslationFailure.SMTLIB_GENERATION,
            solver.rememberedFailureKind(UNSUPPORTED_TYPE, 1)
        )
    }

    /** A query never seen has no recorded outcome, so the short-circuit cannot fire for it. */
    @Test
    fun `an unseen query has no recorded failure kind`() {
        assertEquals(null, solver.rememberedFailureKind("SELECT * FROM users", 1))
    }

    /** Distinct failing queries each get their own entry. */
    @Test
    fun `distinct failing queries are tracked separately`() {
        solver.solve(schemaDto, UNPARSEABLE, 1)
        solver.solve(schemaWithUnsupportedType, UNSUPPORTED_TYPE, 1)

        assertEquals(2, solver.untranslatableQueryCount())
    }

    /**
     * The memo is bounded, so a search that keeps producing new untranslatable queries cannot grow it
     * without limit. Eviction is least-recently-used, which is the right policy here: a query the
     * search has stopped producing is the one worth forgetting.
     *
     * The bound is [EMConfig.sqlZ3CacheSize], applied to this memo and to the result cache alike. Its
     * default was raised from 500 after measuring a system under test that issued 2,153 distinct
     * queries in one search, where the old bound turned nearly half of all cache misses into re-solves
     * of evicted entries rather than genuinely new work.
     */
    @Test
    fun `the memo is bounded`() {
        // A small bound rather than the production default: what is being checked is that eviction
        // happens and keeps the most recent entry, which does not depend on the size of the bound, and
        // this way the cost of the test does not track whatever that default becomes.
        val bound = 64
        solver.initializeCaches(bound)

        repeat(bound + 50) { i -> solver.solve(schemaDto, "$UNPARSEABLE $i", 1) }

        assertTrue(solver.untranslatableQueryCount() <= bound) {
            "expected the memo to stay within $bound, got ${solver.untranslatableQueryCount()}"
        }
        assertTrue(solver.isRememberedUntranslatable("$UNPARSEABLE ${bound + 49}", 1)) {
            "the most recent query must survive eviction"
        }
    }

    /**
     * A query that translates must not be affected. Kept as a regression guard on the short-circuit
     * being consulted only for queries actually recorded as failing — the check runs before parsing,
     * so a bug there would silently disable the solver.
     */
    @Test
    fun `a translatable query is not recorded`() {
        val translatable = "SELECT * FROM users WHERE name = 'Alice'"

        // The Z3 executor is not initialised in this test, so reaching the solver throws rather than
        // returning empty. Either way the query must not end up in the memo.
        runCatching { solver.solve(schemaDto, translatable, 1) }

        assertFalse(solver.isRememberedUntranslatable(translatable, 1)) {
            "a query that parses and generates must not be recorded as untranslatable"
        }
    }
}
