-- http://facasms.fido.gov/
CREATE TABLE "Agencies97" ("AID" INTEGER, "ANo" INTEGER, "FY" TEXT, "AgencyAbbr" TEXT, "AgencyName" TEXT, "Address1" TEXT, "Address2" TEXT, "City" TEXT, "State" TEXT, "Zipcode" TEXT, "Classification" TEXT, "Prefix" TEXT, "FirstName" TEXT, "MiddleName" TEXT, "LastName" TEXT, "Suffix" TEXT, "Title" TEXT, "Phone" TEXT, "Fax" TEXT, "EMail" TEXT, "AgencyURL" TEXT, "DMPrefix" TEXT, "DMFirstName" TEXT, "DMMiddleName" TEXT, "DMLastName" TEXT, "DMSuffix" TEXT, "DMTitle" TEXT, "DMPhone" TEXT, "DMFax" TEXT, "DMEMail" TEXT);
CREATE TABLE "Committees97" ("CID" INTEGER, "CNo" INTEGER, "AID" INTEGER, "ANo" INTEGER, "GID" INTEGER, "FY" TEXT, "CommitteeName" TEXT, "OriginalEstablishmentDate" DATETIME, "TerminationDate" DATETIME, "Prefix" TEXT, "FirstName" TEXT, "MiddleName" TEXT, "LastName" TEXT, "Suffix" TEXT, "Title" TEXT, "Phone" TEXT, "Fax" TEXT, "EMail" TEXT, "PCID" INTEGER, "DMPrefix" TEXT, "DMFirstName" TEXT, "DMMiddleName" TEXT, "DMLastName" TEXT, "DMSuffix" TEXT, "DMTitle" TEXT, "DMPhone" TEXT, "DMFax" TEXT, "DMEMail" TEXT, "AdminInactive" TEXT);
CREATE TABLE "CommitteesInterestAreas" ("CommitteesInterestAreasID" INTEGER, "CNo" INTEGER, "InterestAreasID" INTEGER);
CREATE TABLE "Costs97" ("CostsID" INTEGER, "CID" INTEGER, "CNo" INTEGER, "FY" TEXT, "PersPymtNonFedMemCurFY" INTEGER, "PersPymtFedMemCurFY" INTEGER, "PersPymtFedStaffCurFY" INTEGER, "PersPymtConsultCurFY" INTEGER, "TravPDiemNonFedMemCurFY" INTEGER, "TravPDiemFedMemCurFY" INTEGER, "TravPDiemFedStaffCurFY" INTEGER, "TravPDiemConsultCurFY" INTEGER, "OtherCurFY" INTEGER, "TotalActual" INTEGER, "ActualFedStaffSupportCurrentYr" REAL, "PersPymtNonFedMemEstFY" INTEGER, "PersPymtFedMemEstFY" INTEGER, "PersPymtFedStaffEstFY" INTEGER, "PersPymtConsultEstFY" INTEGER, "TravPDiemNonFedMemEstFY" INTEGER, "TravPDiemFedMemEstFY" INTEGER, "TravPDiemFedStaffEstFY" INTEGER, "TravPDiemConsultEstFY" INTEGER, "OtherEstFY" INTEGER, "TotalEstimated" INTEGER, "EstimatedFedStaffSupportNextYr" REAL);
CREATE TABLE "GeneralInformation97" ("ID" INTEGER, "CID" INTEGER, "CNo" INTEGER, "FY" TEXT, "DepartmentOrAgency" TEXT, "NewCommittee" TEXT, "CurrentCharterDate" DATETIME, "DateOfRenewalCharter" DATETIME, "DateToTerminate" DATETIME, "TerminatedThisFY" TEXT, "SpecificTerminationAuthority" TEXT, "ActualTerminationDate" DATETIME, "EstablishmentAuthority" TEXT, "SpecificEstablishmentAuthority" TEXT, "EffectiveDateOfAuthority" DATETIME, "CommitteeType" TEXT, "Presidential" TEXT, "CommitteeFunction" TEXT, "CommitteeStatus" TEXT, "CommitteeURL" TEXT, "ExemptRenew" TEXT, "PresidentialAppointments" TEXT, "MaxNumberofMembers" TEXT);
CREATE TABLE "InterestAreas" ("InterestAreasID" INTEGER, "CategoryFull" TEXT, "Category" TEXT, "Area" TEXT);
CREATE TABLE "Justifications97" ("ID" INTEGER, "CID" INTEGER, "Cno" INTEGER, "FY" TEXT, "AccomplishesPurpose" TEXT, "BalancedMembership" TEXT, "FrequencyRelevance" TEXT, "WhyThisCommittee" TEXT, "WhyCloseMeetings" TEXT);
CREATE TABLE "LkUp" ("LkUpId" INTEGER, "LkUpType" TEXT, "LkUpValue" TEXT, "LkupSort" INTEGER);
CREATE TABLE "Meetings97" ("ID" INTEGER, "CID" INTEGER, "CNo" INTEGER, "FY" TEXT, "Purpose" TEXT, "MeetingStartDate" DATETIME, "MeetingStopDate" DATETIME, "MeetingType" TEXT, "MinutesLink" TEXT, "Location" TEXT);
CREATE TABLE "Members97" ("MembersID" INTEGER, "CID" INTEGER, "CNo" INTEGER, "FY" TEXT, "Prefix" TEXT, "FirstName" TEXT, "MiddleName" TEXT, "LastName" TEXT, "Suffix" TEXT, "Chairperson" TEXT, "OccupationOrAffiliation" TEXT, "StartDate" DATETIME, "EndDate" DATETIME, "AppointmentType" TEXT, "AppointmentTerm" TEXT, "PayPlan" TEXT, "PaySource" TEXT, "MemberDesignation" TEXT, "RepresentedGroup" TEXT);
CREATE TABLE "Recommendations97" ("ID" INTEGER, "CID" INTEGER, "CNo" INTEGER, "FY" TEXT, "Recommendation" TEXT, "LegislationRequired" TEXT, "LegislationStatus" TEXT, "Remarks" TEXT);
CREATE TABLE "Reports97" ("ID" INTEGER, "CID" INTEGER, "CNo" INTEGER, "FY" TEXT, "ReportTitle" TEXT, "ReportDate" DATETIME, "ReportLink" TEXT, "IsPresidentialActionRequired" TEXT);
CREATE  INDEX "CommitteesInterestAreas_InterestAreasID" ON "CommitteesInterestAreas" ("CNo" );
CREATE  INDEX "CommitteesInterestAreas_OpenInterestAreasOpenCommitteesInterestAreas" ON "CommitteesInterestAreas" ("InterestAreasID" );
CREATE UNIQUE INDEX "CommitteesInterestAreas_PrimaryKey" ON "CommitteesInterestAreas" ("CommitteesInterestAreasID" );
CREATE UNIQUE INDEX "Recommendations97_Committees97Recommendations97" ON "Recommendations97" ("CID" );
CREATE  INDEX "Recommendations97_CNo" ON "Recommendations97" ("CNo" );
CREATE  INDEX "Recommendations97_FY" ON "Recommendations97" ("FY" );
CREATE  INDEX "Recommendations97_ID" ON "Recommendations97" ("ID" );
CREATE UNIQUE INDEX "Recommendations97_PrimaryKey" ON "Recommendations97" ("ID" );
CREATE  INDEX "LkUp_LkUpType" ON "LkUp" ("LkUpType" );
CREATE  INDEX "LkUp_LkUpValue" ON "LkUp" ("LkUpValue" );
CREATE UNIQUE INDEX "LkUp_PrimaryKey" ON "LkUp" ("LkUpId" );
CREATE UNIQUE INDEX "InterestAreas_Area" ON "InterestAreas" ("Area" );
CREATE  INDEX "InterestAreas_Category" ON "InterestAreas" ("Category" );
CREATE  INDEX "InterestAreas_CategoryFull" ON "InterestAreas" ("CategoryFull" );
CREATE UNIQUE INDEX "InterestAreas_PrimaryKey" ON "InterestAreas" ("InterestAreasID" );
CREATE  INDEX "Agencies97_AgencyAbbr" ON "Agencies97" ("AgencyAbbr" );
CREATE  INDEX "Agencies97_AgencyName" ON "Agencies97" ("AgencyName" );
CREATE  INDEX "Agencies97_ANo" ON "Agencies97" ("ANo" );
CREATE  INDEX "Agencies97_FY" ON "Agencies97" ("FY" );
CREATE UNIQUE INDEX "Agencies97_PrimaryKey" ON "Agencies97" ("AID" );
CREATE  INDEX "Members97_Committees97Members97" ON "Members97" ("CID" );
CREATE  INDEX "Members97_CNo" ON "Members97" ("CNo" );
CREATE  INDEX "Members97_FY" ON "Members97" ("FY" );
CREATE  INDEX "Members97_LastName" ON "Members97" ("LastName" );
CREATE UNIQUE INDEX "Members97_PrimaryKey" ON "Members97" ("MembersID" );
CREATE  INDEX "Meetings97_Committees97Meetings97" ON "Meetings97" ("CID" );
CREATE  INDEX "Meetings97_CNo" ON "Meetings97" ("CNo" );
CREATE  INDEX "Meetings97_FY" ON "Meetings97" ("FY" );
CREATE  INDEX "Meetings97_ID" ON "Meetings97" ("ID" );
CREATE UNIQUE INDEX "Meetings97_PrimaryKey" ON "Meetings97" ("ID" );
CREATE UNIQUE INDEX "GeneralInformation97_Committees97GeneralInformation97" ON "GeneralInformation97" ("CID" );
CREATE  INDEX "GeneralInformation97_CNo" ON "GeneralInformation97" ("CNo" );
CREATE  INDEX "GeneralInformation97_FY" ON "GeneralInformation97" ("FY" );
CREATE  INDEX "GeneralInformation97_ID" ON "GeneralInformation97" ("ID" );
CREATE UNIQUE INDEX "GeneralInformation97_PrimaryKey" ON "GeneralInformation97" ("ID" );
CREATE  INDEX "Committees97_AID" ON "Committees97" ("AID" );
CREATE UNIQUE INDEX "Committees97_CID" ON "Committees97" ("CID" );
CREATE  INDEX "Committees97_CNo" ON "Committees97" ("CNo" );
CREATE  INDEX "Committees97_CommitteeName" ON "Committees97" ("CommitteeName" );
CREATE  INDEX "Committees97_FY" ON "Committees97" ("FY" );
CREATE UNIQUE INDEX "Committees97_PrimaryKey" ON "Committees97" ("CID" );
CREATE  INDEX "Reports97_Committees97Reports97" ON "Reports97" ("CID" );
CREATE  INDEX "Reports97_CNo" ON "Reports97" ("CNo" );
CREATE  INDEX "Reports97_FY" ON "Reports97" ("FY" );
CREATE  INDEX "Reports97_ID" ON "Reports97" ("ID" );
CREATE UNIQUE INDEX "Reports97_PrimaryKey" ON "Reports97" ("ID" );
CREATE  INDEX "Reports97_ReportTitle" ON "Reports97" ("ReportTitle" );
CREATE UNIQUE INDEX "Costs97_Committees97Costs97" ON "Costs97" ("CID" );
CREATE  INDEX "Costs97_CNo" ON "Costs97" ("CNo" );
CREATE  INDEX "Costs97_CostsID" ON "Costs97" ("CostsID" );
CREATE  INDEX "Costs97_FY" ON "Costs97" ("FY" );
CREATE UNIQUE INDEX "Costs97_PrimaryKey" ON "Costs97" ("CostsID" );
CREATE UNIQUE INDEX "Justifications97_Committees97Justifications97" ON "Justifications97" ("CID" );
CREATE  INDEX "Justifications97_Cno" ON "Justifications97" ("Cno" );
CREATE  INDEX "Justifications97_FY" ON "Justifications97" ("FY" );
CREATE  INDEX "Justifications97_ID" ON "Justifications97" ("ID" );
CREATE UNIQUE INDEX "Justifications97_PrimaryKey" ON "Justifications97" ("ID" );

