DROP TABLE ORDERS;

DROP TABLE ID_CODES;

  CREATE TABLE ID_CODES (
     CODE1 INT NOT NULL,
     CODE2 INT NOT NULL,
     CODE3 INT NOT NULL,
     CODE4 INT NOT NULL,
     CODE5 INT NOT NULL,
     CODE6 INT NOT NULL,
     CODE7 INT NOT NULL,
     CODE8 INT NOT NULL,
     CODE9 INT NOT NULL,
     CODE10 INT NOT NULL,
     CODE11 INT NOT NULL,
     CODE12 INT NOT NULL,
     CODE13 INT NOT NULL,
     CODE14 INT NOT NULL,
     CODE15 INT NOT NULL,
     PRIMARY KEY (CODE1, CODE2, CODE3, CODE4, CODE5,
       CODE6, CODE7, CODE8, CODE9, CODE10,
       CODE11, CODE12, CODE13, CODE14, CODE15));

  CREATE TABLE ORDERS (
     CODE1 INT NOT NULL,
     CODE2 INT NOT NULL,
     CODE3 INT NOT NULL,
     CODE4 INT NOT NULL,
     CODE5 INT NOT NULL,
     CODE6 INT NOT NULL,
     CODE7 INT NOT NULL,
     CODE8 INT NOT NULL,
     CODE9 INT NOT NULL,
     CODE10 INT NOT NULL,
     CODE11 INT NOT NULL,
     CODE12 INT NOT NULL,
     CODE13 INT NOT NULL,
     CODE14 INT NOT NULL,
     CODE15 INT NOT NULL,
     TITLE VARCHAR (80),
     COST NUMERIC(5,2),
     FOREIGN KEY (CODE1, CODE2, CODE3, CODE4, CODE5,
       CODE6, CODE7, CODE8, CODE9, CODE10,
       CODE11, CODE12, CODE13, CODE14, CODE15)
     REFERENCES ID_CODES);
