DROP TABLE S;

DROP TABLE T;

CREATE TABLE T 
(
     A VARCHAR(1), B VARCHAR(1), C VARCHAR(1),
     CONSTRAINT UniqueOnColsAandB UNIQUE (A, B)
);

CREATE TABLE S 
(
     X VARCHAR(1), Y VARCHAR(1), Z VARCHAR(1),
     CONSTRAINT RefToColsAandB FOREIGN KEY (X, Y)
     REFERENCES T (A, B)
);
