DROP TABLE S;

DROP TABLE T;

CREATE TABLE T 
(
     A CHAR, B CHAR, C CHAR,
     CONSTRAINT UniqueOnColsAandB UNIQUE (A, B)
);

CREATE TABLE S 
(
     X CHAR, Y CHAR, Z CHAR,
     CONSTRAINT RefToColsAandB FOREIGN KEY (X, Y)
     REFERENCES T (A, B)
);
