DROP TABLE S;

DROP TABLE T;

CREATE TABLE T 
(
     A CHAR NOT NULL, B CHAR NOT NULL, C CHAR NOT NULL,
     CONSTRAINT UniqueOnColsAandB UNIQUE (A, B)
);

CREATE TABLE S 
(
     X CHAR NOT NULL, Y CHAR NOT NULL, Z CHAR NOT NULL,
     CONSTRAINT RefToColsAandB FOREIGN KEY (X, Y)
     REFERENCES T (A, B)
);
