DROP TABLE S;

DROP TABLE T;

CREATE TABLE T 
(
     A VARCHAR(10) NOT NULL, B VARCHAR(10) NOT NULL, C VARCHAR(10) NOT NULL,
     CONSTRAINT UniqueOnColsAandB UNIQUE (A, B)
);

CREATE TABLE S 
(
     X VARCHAR(10) NOT NULL, Y VARCHAR(10) NOT NULL, Z VARCHAR(10) NOT NULL,
     CONSTRAINT RefToColsAandB FOREIGN KEY (X, Y)
     REFERENCES T (A, B)
);
