DROP TABLE userrecord CASCADE;

CREATE TABLE userrecord
( 
  NAME char(50), 
  ZIP char(5), 
  SSN int NOT NULL, 
  AGE int, 
  SEX char(50), 
  MARITAL char(50), 
  RACE char(50), 
  TAXSTAT char(50), 
  DETAIL char(100), 
  HOUSEHOLDDETAIL char(100), 
  FATHERORIGIN char(50), 
  MOTHERORIGIN char(50), 
  BIRTHCOUNTRY char(50), 
  CITIZENSHIP char(50), 
  PRIMARY KEY (SSN) 
);

DROP TABLE education CASCADE;

CREATE TABLE education 
( 
  SSN int NOT NULL, 
  EDUCATION char(50),
  EDUENROLL char(50), 
  PRIMARY KEY (SSN),
  FOREIGN KEY (SSN) REFERENCES userrecord (SSN)
);

DROP TABLE employmentstat CASCADE;

CREATE TABLE employmentstat
( 
  SSN int NOT NULL, 
  UNEMPLOYMENTREASON char(50), 
  EMPLOYMENTSTAT char(50), 
  PRIMARY KEY (SSN),
  FOREIGN KEY (SSN) REFERENCES userrecord (SSN) 
);

DROP TABLE geo CASCADE;

CREATE TABLE geo 
( 
  REGION char(50) NOT NULL, 
  RESSTATE char(50) NOT NULL, 
  PRIMARY KEY (RESSTATE) 
);

DROP TABLE industry CASCADE;

CREATE TABLE industry 
( 
  INDUSTRYCODE int NOT NULL, 
  INDUSTRY char(50),
  STABILITY int, 
  PRIMARY KEY (INDUSTRYCODE) 
);

DROP TABLE investment CASCADE;

CREATE TABLE investment 
( 
  SSN int NOT NULL, 
  CAPITALGAINS int,
  CAPITALLOSSES int, 
  STOCKDIVIDENDS int, 
  PRIMARY KEY (SSN),
  FOREIGN KEY (SSN) REFERENCES userrecord (SSN)
);

DROP TABLE occupation CASCADE;

CREATE TABLE occupation 
( 
  OCCUPATIONCODE int NOT NULL, 
  OCCUPATION char(50), 
  STABILITY int, 
  PRIMARY KEY (OCCUPATIONCODE) 
);

DROP TABLE job CASCADE;

CREATE TABLE job 
( 
  SSN int NOT NULL, 
  WORKCLASS char(50), 
  INDUSTRYCODE int, 
  OCCUPATIONCODE int, 
  UNIONMEMBER char(50), 
  EMPLOYERSIZE int,
  WEEKWAGE int, 
  SELFEMPLOYED smallint, 
  WORKWEEKS int, 
  PRIMARY KEY (SSN),
  FOREIGN KEY (OCCUPATIONCODE) REFERENCES occupation (OCCUPATIONCODE), 
  FOREIGN KEY (SSN) REFERENCES userrecord (SSN), 
  FOREIGN KEY (INDUSTRYCODE) REFERENCES industry (INDUSTRYCODE)
);

DROP TABLE migration CASCADE; 

CREATE TABLE migration 
( 
  SSN int NOT NULL, 
  MIGRATIONCODE char(50),
  MIGRATIONDISTANCE char(50), 
  MIGRATIONMOVE char(50),
  MIGRATIONFROMSUNBELT char(50), 
  PRIMARY KEY (SSN),
  FOREIGN KEY (SSN) REFERENCES userrecord (SSN) 
);



DROP TABLE stateabbv CASCADE;

CREATE TABLE stateabbv 
( 
  ABBV char(2) NOT NULL, 
  NAME char(50) NOT NULL
);



DROP TABLE wage CASCADE;

CREATE TABLE wage 
( 
  INDUSTRYCODE int NOT NULL, 
  OCCUPATIONCODE int NOT NULL, 
  MEANWEEKWAGE int, 
  PRIMARY KEY (INDUSTRYCODE, OCCUPATIONCODE),
  FOREIGN KEY (INDUSTRYCODE) REFERENCES industry (INDUSTRYCODE),
  FOREIGN KEY (OCCUPATIONCODE) REFERENCES occupation (OCCUPATIONCODE) 
);

DROP TABLE youth CASCADE;

CREATE TABLE youth
(
  SSN int NOT NULL, 
  PARENTS char(50), 
  PRIMARY KEY (SSN),
  FOREIGN KEY (SSN) REFERENCES userrecord (SSN)	 
);

DROP TABLE ziptable CASCADE;

CREATE TABLE ziptable 
( 
  ZIP char(5), 
  CITY char(20), 
  STATENAME char(20), 
  COUNTY char(20) 
);

