-- http://www.bioconductor.org/packages/2.12/bioc/html/SRAdb.html

CREATE TABLE col_desc 
( col_desc_ID REAL,
	table_name TEXT,
	field_name TEXT,
	type TEXT,
	description TEXT,
	value_list TEXT,
	sradb_updated TEXT 
);
CREATE TABLE experiment 
( experiment_ID REAL,
	bamFile TEXT,
	fastqFTP TEXT,
	experiment_alias TEXT,
	experiment_accession TEXT,
	broker_name TEXT,
	center_name TEXT,
	title TEXT,
	study_name TEXT,
	study_accession TEXT,
	design_description TEXT,
	sample_name TEXT,
	sample_accession TEXT,
	sample_member TEXT,
	library_name TEXT,
	library_strategy TEXT,
	library_source TEXT,
	library_selection TEXT,
	library_layout TEXT,
	targeted_loci TEXT,
	library_construction_protocol TEXT,
	spot_length INTEGER,
	adapter_spec TEXT,
	read_spec TEXT,
	platform TEXT,
	instrument_model TEXT,
	platform_parameters TEXT,
	sequence_space TEXT,
	base_caller TEXT,
	quality_scorer TEXT,
	number_of_levels INTEGER,
	multiplier TEXT,
	qtype TEXT,
	sra_link TEXT,
	experiment_url_link TEXT,
	xref_link TEXT,
	experiment_entrez_link TEXT,
	ddbj_link TEXT,
	ena_link TEXT,
	experiment_attribute TEXT,
	submission_accession TEXT,
	sradb_updated TEXT 
);
CREATE TABLE metaInfo (name varchar(50), value varchar(50));
CREATE TABLE run 
( run_ID REAL,
	bamFile TEXT,
	run_alias TEXT,
	run_accession TEXT,
	broker_name TEXT,
	instrument_name TEXT,
	run_date TEXT,
	run_file TEXT,
	run_center TEXT,
	total_data_blocks INTEGER,
	experiment_accession TEXT,
	experiment_name TEXT,
	sra_link TEXT,
	run_url_link TEXT,
	xref_link TEXT,
	run_entrez_link TEXT,
	ddbj_link TEXT,
	ena_link TEXT,
	run_attribute TEXT,
	submission_accession TEXT,
	sradb_updated TEXT 
);
CREATE TABLE sample 
( sample_ID REAL,
	sample_alias TEXT,
	sample_accession TEXT,
	broker_name TEXT,
	center_name TEXT,
	taxon_id INTEGER,
	scientific_name TEXT,
	common_name TEXT,
	anonymized_name TEXT,
	individual_name TEXT,
	description TEXT,
	sra_link TEXT,
	sample_url_link TEXT,
	xref_link TEXT,
	sample_entrez_link TEXT,
	ddbj_link TEXT,
	ena_link TEXT,
	sample_attribute TEXT,
	submission_accession TEXT,
	sradb_updated TEXT 
);
CREATE TABLE sra 
( sra_ID REAL,
	SRR_bamFile TEXT,
	SRX_bamFile TEXT,
	SRX_fastqFTP TEXT,
	run_ID REAL,
	run_alias TEXT,
	run_accession TEXT,
	run_date TEXT,
	updated_date TEXT,
	spots INTEGER,
	bases INTEGER,
	run_center TEXT,
	experiment_name TEXT,
	run_url_link TEXT,
	run_entrez_link TEXT,
	run_attribute TEXT,
	experiment_ID REAL,
	experiment_alias TEXT,
	experiment_accession TEXT,
	experiment_title TEXT,
	study_name TEXT,
	sample_name TEXT,
	design_description TEXT,
	library_name TEXT,
	library_strategy TEXT,
	library_source TEXT,
	library_selection TEXT,
	library_layout TEXT,
	library_construction_protocol TEXT,
	adapter_spec TEXT,
	read_spec TEXT,
	platform TEXT,
	instrument_model TEXT,
	instrument_name TEXT,
	platform_parameters TEXT,
	sequence_space TEXT,
	base_caller TEXT,
	quality_scorer TEXT,
	number_of_levels INTEGER,
	multiplier TEXT,
	qtype TEXT,
	experiment_url_link TEXT,
	experiment_entrez_link TEXT,
	experiment_attribute TEXT,
	sample_ID REAL,
	sample_alias TEXT,
	sample_accession TEXT,
	taxon_id INTEGER,
	common_name TEXT,
	anonymized_name TEXT,
	individual_name TEXT,
	description TEXT,
	sample_url_link TEXT,
	sample_entrez_link TEXT,
	sample_attribute TEXT,
	study_ID REAL,
	study_alias TEXT,
	study_accession TEXT,
	study_title TEXT,
	study_type TEXT,
	study_abstract TEXT,
	center_project_name TEXT,
	study_description TEXT,
	study_url_link TEXT,
	study_entrez_link TEXT,
	study_attribute TEXT,
	related_studies TEXT,
	primary_study TEXT,
	submission_ID REAL,
	submission_accession TEXT,
	submission_comment TEXT,
	submission_center TEXT,
	submission_lab TEXT,
	submission_date TEXT,
	sradb_updated TEXT 
);
-- CREATE VIRTUAL TABLE sra_ft USING fts3 ( SRR_bamFile,SRX_bamFile,SRX_fastqFTP,run_ID,run_alias,run_accession,run_date,updated_date,spots,bases,run_center,experiment_name,run_url_link,run_entrez_link,run_attribute,experiment_ID,experiment_alias,experiment_accession,experiment_title,study_name,sample_name,design_description,library_name,library_strategy,library_source,library_selection,library_layout,library_construction_protocol,adapter_spec,read_spec,platform,instrument_model,instrument_name,platform_parameters,sequence_space,base_caller,quality_scorer,number_of_levels,multiplier,qtype,experiment_url_link,experiment_entrez_link,experiment_attribute,sample_ID,sample_alias,sample_accession,taxon_id,common_name,anonymized_name,individual_name,description,sample_url_link,sample_entrez_link,sample_attribute,study_ID,study_alias,study_accession,study_title,study_type,study_abstract,center_project_name,study_description,study_url_link,study_entrez_link,study_attribute,related_studies,primary_study,submission_ID,submission_accession,submission_comment,submission_center,submission_lab,submission_date,sradb_updated );

CREATE TABLE "sra_ft_content"(docid INTEGER PRIMARY KEY, "c0SRR_bamFile" TEXT,
	"c1SRX_bamFile" TEXT, "c2SRX_fastqFTP" TEXT, "c3run_ID" TEXT, "c4run_alias"
	TEXT, "c5run_accession" TEXT, "c6run_date" TEXT, "c7updated_date" TEXT,
	"c8spots" TEXT, "c9bases" TEXT, "c10run_center" TEXT, "c11experiment_name"
	TEXT, "c12run_url_link" TEXT, "c13run_entrez_link" TEXT, "c14run_attribute"
	TEXT, "c15experiment_ID" TEXT, "c16experiment_alias" TEXT,
	"c17experiment_accession" TEXT, "c18experiment_title" TEXT, "c19study_name"
	TEXT, "c20sample_name" TEXT, "c21design_description" TEXT,
	"c22library_name" TEXT, "c23library_strategy" TEXT, "c24library_source"
	TEXT, "c25library_selection" TEXT, "c26library_layout" TEXT,
	"c27library_construction_protocol" TEXT, "c28adapter_spec" TEXT, "c29read_spec" TEXT,
	"c30platform" TEXT, "c31instrument_model" TEXT, "c32instrument_name" TEXT,
	"c33platform_parameters" TEXT, "c34sequence_space" TEXT, "c35base_caller" TEXT,
	"c36quality_scorer" TEXT, "c37number_of_levels" TEXT, "c38multiplier" TEXT, "c39qtype" TEXT,
	"c40experiment_url_link" TEXT, "c41experiment_entrez_link" TEXT,
	"c42experiment_attribute" TEXT, "c43sample_ID" TEXT, "c44sample_alias" TEXT,
	"c45sample_accession" TEXT, "c46taxon_id" TEXT, "c47common_name" TEXT,
	"c48anonymized_name" TEXT, "c49individual_name" TEXT, "c50description" TEXT,
	"c51sample_url_link" TEXT, "c52sample_entrez_link" TEXT, "c53sample_attribute" TEXT,
	"c54study_ID" TEXT, "c55study_alias" TEXT, "c56study_accession" TEXT, "c57study_title" TEXT,
	"c58study_type" TEXT, "c59study_abstract" TEXT, "c60center_project_name" TEXT,
	"c61study_description" TEXT, "c62study_url_link" TEXT, "c63study_entrez_link" TEXT,
	"c64study_attribute" TEXT, "c65related_studies" TEXT, "c66primary_study" TEXT,
	"c67submission_ID" TEXT, "c68submission_accession" TEXT, "c69submission_comment" TEXT,
	"c70submission_center" TEXT, "c71submission_lab" TEXT, "c72submission_date" TEXT,
	"c73sradb_updated" TEXT);


CREATE TABLE "sra_ft_segdir"(level INTEGER,idx INTEGER,start_block
	INTEGER,leaves_end_block INTEGER,end_block INTEGER,root TEXT,PRIMARY
	KEY(level, idx));


CREATE TABLE "sra_ft_segments"(blockid INTEGER PRIMARY KEY, block TEXT);
CREATE TABLE study 
( study_ID REAL,
	study_alias TEXT,
	study_accession TEXT,
	study_title TEXT,
	study_type TEXT,
	study_abstract TEXT,
	broker_name TEXT,
	center_name TEXT,
	center_project_name TEXT,
	study_description TEXT,
	related_studies TEXT,
	primary_study TEXT,
	sra_link TEXT,
	study_url_link TEXT,
	xref_link TEXT,
	study_entrez_link TEXT,
	ddbj_link TEXT,
	ena_link TEXT,
	study_attribute TEXT,
	submission_accession TEXT,
	sradb_updated TEXT 
);
CREATE TABLE submission 
( submission_ID REAL,
	submission_alias TEXT,
	submission_accession TEXT,
	submission_comment TEXT,
	files TEXT,
	broker_name TEXT,
	center_name TEXT,
	lab_name TEXT,
	submission_date TEXT,
	sra_link TEXT,
	submission_url_link TEXT,
	xref_link TEXT,
	submission_entrez_link TEXT,
	ddbj_link TEXT,
	ena_link TEXT,
	submission_attribute TEXT,
	sradb_updated TEXT 
);
CREATE INDEX experiment_acc_idx on experiment (experiment_accession);
CREATE INDEX run_acc_idx on run (run_accession);
CREATE INDEX sample_acc_idx on sample (sample_accession);
CREATE INDEX sra_experiment_acc_idx on sra (experiment_accession);
CREATE INDEX sra_run_acc_idx on sra (run_accession);
CREATE INDEX sra_sample_acc_idx on sra (sample_accession);
CREATE INDEX sra_study_acc_idx on sra (study_accession);
CREATE INDEX sra_submission_acc_idx on sra (submission_accession);
CREATE INDEX study_acc_idx on study (study_accession);
CREATE INDEX submission_acc_idx on submission (submission_accession);

