-- ChangeSet 2: Create tag_derived view
CREATE VIEW tag_derived AS
SELECT
    T.ID AS TAG_ID,
FROM
    TAG T LEFT JOIN ACTIVITY_PROPERTIES_TAG APT ON T.ID = APT.TAG_ID
          INNER JOIN ACTIVITY_PROPERTIES AP ON (APT.ACTIVITY_PROPERTIES_ID = AP.ID AND AP.PUBLISHING_ACTIVITY_ID IS NOT NULL)
GROUP BY
    T.ID;
