<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.evomaster</groupId>
        <artifactId>evomaster-core-extra</artifactId>
        <version>6.2.1-SNAPSHOT</version>
    </parent>
    <artifactId>networknt-schema-validator</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.networknt</groupId>
            <artifactId>json-schema-validator</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.ethlo.time</groupId>
            <artifactId>itu</artifactId>
            <version>1.14.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>unpack-networknt</id>
                        <phase>process-resources</phase>
                        <goals><goal>unpack</goal></goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.networknt</groupId>
                                    <artifactId>json-schema-validator</artifactId>
                                    <version>${networknt.json-schema-validator.version}</version>
                                    <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>isolate-networknt-messages</id>
                        <phase>process-resources</phase>
                        <goals><goal>run</goal></goals>
                        <configuration>
                            <target>
                                <mkdir dir="${project.build.outputDirectory}/org/evomaster/networknt/messages"/>
                                <move todir="${project.build.outputDirectory}/org/evomaster/networknt/messages">
                                    <fileset dir="${project.build.outputDirectory}" includes="jsv-messages*.properties"/>
                                </move>
                                <replace file="${project.build.outputDirectory}/META-INF/native-image/com.networknt/json-schema-validator/resource-config.json"
                                         token="jsv-messages.*properties"
                                         value="org/evomaster/networknt/messages/jsv-messages.*properties"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
