package org.evomaster.client.java.controller.api.dto.database.neo4j;

import org.evomaster.client.java.controller.api.dto.database.operations.Neo4jPropertyTypeDto;

import java.util.ArrayList;
import java.util.List;

/**
 * A property of the nodes of a Neo4j entity, as declared in the SUT's mapping of that entity.
 */
public class Neo4jEntityPropertyDto {

    /**
     * Name of the property in the graph.
     */
    public String name;

    /**
     * Type the property is stored as.
     */
    public Neo4jPropertyTypeDto type;

    /**
     * Whether the property identifies the node.
     */
    public Boolean isId;

    /**
     * Whether the value is generated by the database or the mapping, so the SUT never assigns it.
     */
    public Boolean isGenerated;

    /**
     * Smallest value the property can hold when the SUT reads it back, if its Java type is narrower
     * than the graph's integer; null otherwise.
     */
    public Long minValue;

    /**
     * Largest value the property can hold when the SUT reads it back, if its Java type is narrower
     * than the graph's integer; null otherwise.
     */
    public Long maxValue;

    /**
     * The only values the property accepts, when it is backed by an enum; empty otherwise.
     */
    public List<String> enumValues = new ArrayList<>();

    /**
     * Default constructor
     */
    public Neo4jEntityPropertyDto() {
    }
}
