package org.evomaster.client.java.instrumentation;

import java.io.Serializable;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * A property of a Neo4j entity class, i.e. a field the SUT maps to a node property.
 */
public class Neo4jEntityProperty implements Serializable {

    /** Property name as stored in the graph, i.e. the field name unless overridden in the mapping. */
    private final String name;

    /** Property type in the graph: one of STRING, INTEGER, FLOAT or BOOLEAN. */
    private final String type;

    /** Whether the property identifies the node in the mapping. */
    private final boolean id;

    /** Whether the value of the property is generated by the database or the mapping, so never chosen by the SUT. */
    private final boolean generated;

    /** Smallest value the Java type of the field holds, for an INTEGER narrower than long; null otherwise. */
    private final Long minValue;

    /** Largest value the Java type of the field holds, for an INTEGER narrower than long; null otherwise. */
    private final Long maxValue;

    /** The constants of the field's enum type, for a STRING backed by an enum; empty otherwise. */
    private final List<String> enumValues;

    /**
     * @param name property name in the graph
     * @param type STRING, INTEGER, FLOAT or BOOLEAN
     * @param id whether it is the identifier of the entity
     * @param generated whether its value is generated rather than assigned
     * @param minValue lower bound of the Java type, or null
     * @param maxValue upper bound of the Java type, or null
     * @param enumValues constants of the enum type, or an empty list
     */
    public Neo4jEntityProperty(String name, String type, boolean id, boolean generated,
                               Long minValue, Long maxValue, List<String> enumValues) {
        this.name = Objects.requireNonNull(name);
        this.type = Objects.requireNonNull(type);
        this.id = id;
        this.generated = generated;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.enumValues = Collections.unmodifiableList(enumValues == null ? Collections.<String>emptyList() : enumValues);
    }

    public Neo4jEntityProperty(String name, String type, boolean id, boolean generated) {
        this(name, type, id, generated, null, null, null);
    }

    public String getName() {
        return name;
    }

    public String getType() {
        return type;
    }

    public boolean isId() {
        return id;
    }

    public boolean isGenerated() {
        return generated;
    }

    public Long getMinValue() {
        return minValue;
    }

    public Long getMaxValue() {
        return maxValue;
    }

    public List<String> getEnumValues() {
        return enumValues;
    }

    @Override
    public String toString() {
        return name + ":" + type + (id ? " (id)" : "") + (generated ? " (generated)" : "");
    }
}
