package org.evomaster.client.java.controller.db.dsl;

import org.evomaster.client.java.controller.api.dto.database.operations.InsertionDto;
import org.evomaster.client.java.controller.api.dto.database.operations.InsertionEntryDto;

import java.util.ArrayList;
import java.util.List;

/**
 * DSL (Domain Specific Language) for operations on
 * the SQL Database
 */
public class SqlDsl implements SequenceDsl, StatementDsl {

    private List<InsertionDto> list = new ArrayList<>();

    private SqlDsl() {
    }

    /**
     * @return a DSL object to create SQL operations
     */
    public static SequenceDsl sql() {

        return new SqlDsl();
    }

    @Override
    public StatementDsl insertInto(String tableName, Long id) {

        checkDsl();

        if (tableName == null || tableName.isEmpty()) {
            throw new IllegalArgumentException("Unspecified table");
        }

        if (id != null && list.stream().anyMatch(t -> id.equals(t.id))) {
            throw new IllegalArgumentException("Non-unique id: " + id);
        }


        InsertionDto dto = new InsertionDto();
        dto.targetTable = tableName;
        dto.id = id;

        list.add(dto);

        return this;
    }

    @Override
    public StatementDsl d(String columnName, String printableValue) {

        checkDsl();

        if (columnName == null || columnName.isEmpty()) {
            throw new IllegalArgumentException("Unspecified variable");
        }

        InsertionEntryDto entry = new InsertionEntryDto();
        entry.variableName = columnName;
        entry.printableValue = printableValue;

        current().data.add(entry);

        return this;
    }

    public StatementDsl r(String columnName, long insertionId, boolean keepAutoGeneratedValue) {
        return r(columnName, insertionId, keepAutoGeneratedValue, true);
    }

    public StatementDsl r(String columnName, long insertionId, boolean keepAutoGeneratedValue, boolean isInList) {
        checkDsl();

        if (columnName == null || columnName.isEmpty()) {
            throw new IllegalArgumentException("Unspecified variable");
        }

        if (isInList && list.stream().noneMatch(t -> t.id != null && t.id.equals(insertionId))) {
            throw new IllegalArgumentException("Non-existing previous insertion with id: " + insertionId);
        }

        InsertionEntryDto entry = new InsertionEntryDto();
        entry.variableName = columnName;
        entry.foreignKeyToPreviouslyGeneratedRow = insertionId;
        entry.keepAutoGeneratedValue = keepAutoGeneratedValue;

        current().data.add(entry);

        return this;

    }

    @Override
    public StatementDsl r(String columnName, long insertionId) {
        return r(columnName, insertionId, false);
    }

    @Override
    public SequenceDsl and() {
        return this;
    }

    @Override
    public List<InsertionDto> dtos() {

        List<InsertionDto> tmp = list;
        list = null;

        return tmp;
    }


    private InsertionDto current() {
        return list.get(list.size() - 1);
    }

    private void checkDsl() {
        if (list == null) {
            throw new IllegalStateException("DTO was already built for this object");
        }
    }

}
