(declare-datatypes () ((UsersRow (id-name-age-points (ID Int) (NAME String) (AGE Int) (POINTS Int) ))))
(declare-const users1 UsersRow)
(declare-const users2 UsersRow)
(assert (= (NAME users1) "agus"))
(assert (= (NAME users2) "agus"))
(assert (or (< (POINTS users1) 4) (> (POINTS users1) 6)))
(assert (or (< (POINTS users2) 4) (> (POINTS users2) 6)))
(assert (and (> (AGE users1) 18) (< (AGE users1) 100)))
(assert (and (> (AGE users2) 18) (< (AGE users2) 100)))
(assert (<= (POINTS users1) 10))
(assert (<= (POINTS users2) 10))
(assert (>= (POINTS users1) 0))
(assert (>= (POINTS users2) 0))
(assert (and (> (AGE users1) 30) (= (POINTS users1) 7)))
(assert (and (> (AGE users2) 30) (= (POINTS users2) 7)))
(check-sat)
(get-value (users1))
(get-value (users2))