from drf_spectacular.utils import extend_schema
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .serializers import ItemSerializer, LoginSerializer

# Test-only static credentials/token for black-box auth demonstration.
VALID_USERNAME = "foo"
VALID_PASSWORD = "123"
VALID_TOKEN = "secret-token-123"

# Deterministic, stateless data. The SUT keeps no persistent state, so the tests
# generated by the black-box fuzzer produce the same result every time they re-run.
MAX_ITEM_ID = 10
FIXED_ITEMS = [
    {"id": 1, "name": "alpha", "price": 10},
    {"id": 2, "name": "beta", "price": 20},
]


@extend_schema(methods=["GET"], responses={200: ItemSerializer(many=True)})
@extend_schema(methods=["POST"], request=ItemSerializer, responses={201: ItemSerializer, 400: None})
@api_view(["GET", "POST"])
def items(request):
    if request.method == "GET":
        return Response(FIXED_ITEMS)
    # POST: validate the body but do not persist anything
    serializer = ItemSerializer(data=request.data)
    if not serializer.is_valid():
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    return Response({"id": 1, **serializer.validated_data}, status=status.HTTP_201_CREATED)


@extend_schema(methods=["GET"], responses={200: ItemSerializer, 404: None})
@extend_schema(methods=["PUT"], request=ItemSerializer, responses={200: ItemSerializer, 400: None, 404: None})
@extend_schema(methods=["DELETE"], responses={204: None})
@api_view(["GET", "PUT", "DELETE"])
def item_detail(request, item_id):
    # DELETE is idempotent: it always succeeds, so the clean-up DELETEs added by the
    # fuzzer after a POST never produce a 404 (which would otherwise break its invariant)
    if request.method == "DELETE":
        return Response(status=status.HTTP_204_NO_CONTENT)

    if not (1 <= item_id <= MAX_ITEM_ID):
        return Response({"error": "not found"}, status=status.HTTP_404_NOT_FOUND)

    if request.method == "GET":
        return Response({"id": item_id, "name": "item", "price": item_id * 10})

    # PUT
    serializer = ItemSerializer(data=request.data)
    if not serializer.is_valid():
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    return Response({"id": item_id, **serializer.validated_data})


@extend_schema(request=LoginSerializer, responses={200: None, 401: None})
@api_view(["POST"])
def login(request):
    username = request.data.get("username")
    password = request.data.get("password")
    if username == VALID_USERNAME and password == VALID_PASSWORD:
        return Response({"access_token": VALID_TOKEN})
    return Response({"error": "invalid credentials"}, status=status.HTTP_401_UNAUTHORIZED)


@extend_schema(responses={200: None, 401: None})
@api_view(["GET"])
def secure_check(request):
    token = request.headers.get("Authorization")
    if token == VALID_TOKEN:
        return Response({"message": "granted"})
    return Response({"error": "unauthorized"}, status=status.HTTP_401_UNAUTHORIZED)
