name: Release on GitHub


## Run only when we push a tag. See "docs/release.md" instructions
on:
  push:
    tags:
      - "test*"

env:
  evomaster-version: 5.2.1
  jdk-jar: 17
  jdk-jpackage: 21
  java-distribution: temurin
  retention-days: 1


jobs:

  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6


##########################################################
  build-Python:
    needs: build-base
    name: Build Python Distribution and Publish on PyPi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install 'build'
        shell: bash
        run: |
          pip install build

      - name: Build Python Wheel
        shell: bash
        working-directory: ./pypi-distribution
        run: |
          rm -fr dist
          python -m build

      - uses: actions/upload-artifact@v7
        with:
          path: ./pypi-distributiondist/dist/*.whl
          retention-days: ${{env.retention-days}}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./pypi-distribution/dist
          password: ${{ secrets.PYPI_API_TOKEN }}


# FIXME update